### PR TITLE
Vendor curl from BinaryBuilder rather than using curl/OpenSSL

### PR DESCRIPTION
**Pull request by mkitti**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mkitti** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Please don't. If we are going to do this, we might as well re-package the julia binary.

**Comment by mkitti** [comment]
Let's just see if this builds or not. The recipe that used to build no longer builds, so we're stuck at the moment.

If this succeeds, we can next try USE_BINARYBUILDER_CURL=0 to build the vendored curl from source. Next we can bump the version to 7.81 and see if we can align the configuration options in 

https://github.com/JuliaLang/julia/blob/acb6e16b5b941cd3efc7ddec2217a4497120f8bb/deps/curl.mk#L52-L58

**Comment by mkitti** [comment]
Umm... ok. This is exactly where the build stopped in #176, and we basically did not change anything versus #170.

I have no idea what is happening.

**Comment by ngam** [comment]
> Umm... ok. This is exactly where the build stopped in #176, and we basically did not change anything versus #170.
> 
> I have no idea what is happening.

It's the curl. That's the issue here. Curl is still in the conda list, at 7.81.0

**Comment by ngam** [comment]
> > Umm... ok. This is exactly where the build stopped in #176, and we basically did not change anything versus #170.
> > I have no idea what is happening.
> 
> It's the curl. That's the issue here. Curl is still in the conda list, at 7.81.0

Nothing else is different.

**Comment by ngam** [comment]
> Please don't. If we are going to do this, we might as well re-package the julia binary.

@isuruf could you please weigh in here #175? We need to figure out a sustainable solution to this mess, and obviously the upstream peeps aren't going to help

**Comment by ngam** [comment]
@mkitti could you please verify that the tar from upstream is the same as a week ago? It should be ... since sha256 didn't change, but I don't know. And could we check if any curl-like deps (git, ssh, etc.) has changed in the past week on conda-forge side?

**Comment by ngam** [comment]
We got a similar error with libgit fwiw. There is a reason the osx build is going ahead --- libgit is disabled there

**Comment by ngam** [comment]
@mkitti 

https://github.com/conda-forge/libgit2-feedstock/blob/df856aa0a1cba23aea2d34142e3053311ab40003/recipe/meta.yaml#L30

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
Closing this since we now know what the problem is exactly.

**Pull request closed without merging**
