### PR TITLE
1.9.0-DEV

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@mkitti same issue with  cmdlineargs for 1.9 dev, though this is pretty much expected (1.8 beta and 1.9 dev should be pretty similar)

Given this passes locally, I am fine skipping the test for now. 

In total we have only 6 hours for ```all``` tests (on osx). We seem to have a serious problem with the CI linux64. I believe that might be a memory/disk issue of some sort (my local linux64 machine is a lowly 10+ yr old laptop...)

**Comment by mkitti** [comment]
I'm confused. `cmdlineargs` passes now?

**Comment by ngam** [comment]
Yes, the issue is basically that it gets stuck for some bizarre reason. Now the osx one is stuck at downloads or something. One way to unlock this is to do the tests one by one maybe.

Also, the Pkg.add("sundials") doesn't work --- same issue, it just gets stuck somewhere.

This can happen locally, and usually you can just redo it and it would just work. So I really don't know if it is something we can address or not...

**Comment by ngam** [comment]
Also, I am starting to think that cross-pollination isn't that good of an idea. I like having julia as part of conda-forge, but I don't really see the point of the excessive customization (especially when it comes to system deps, etc.). (The custom depot is our most valuable addition imo --- that was really good, so thank you!)

I have been working more and more with julia proper, writing a simple package, and I just am not sure if having all these complex dependency stuff is worth it. Julia plays nice with having all of its deps hidden from the rest of the system so to speak, and we could simply follow suite with a simple `make` build. But idk, but maybe for the packages that like to cross-pollinate more heavily (pysr, esm, etc.) they may still want something like this with the system deps (though I doubt it would make a difference — it would be good to see actual example of failures if we set a "pure" julia, e.g. repackaging the upstream)

**Comment by ngam** [comment]
What are your thoughts / ideas about the path forward?

**Comment by mkitti** [comment]
As for what else is happening, I would really like to understand it.
Do you have the same issue with official Julia?

When it does get stuck,  is there any pattern?

**Comment by ngam** [comment]
juliaup might be nice to have --- looks pretty simple to build: https://github.com/Homebrew/homebrew-core/blob/78294ee9aabcf0337ad0a4943a43772c8005469e/Formula/juliaup.rb#L28-L29

But one interest of mine is making sure we are making stuff accessible. Not really sure what juliaup uses behind the scenes, but many academic places open to some conda channels + github and nothing else (not even pypi) and so if the downloading happens through third-party websites/hosts, then that would be less than ideal...

**Comment by ngam** [comment]
Another observation that may help you think through this:

I noticed that Pkg.add works significantly better and faster if you do it incrementally, so add one pkg, then another, then a third, etc. rather than adding all of them at once or adding a package that has like 100 dependency. Does that make sense?

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
```

Total time: 0:55:20.1
CPU usage: sys=0:02:22.0, user=1:06:14.6
Maximum memory usage observed: 5.3G
Total disk usage observed (not including envs): 1.4M

```

Not sure if this is a lot or not

**Pull request merged**
