### PR TITLE
Pin suitesparse to 5.4.0 in run for Julia 1.6.2

### PR DESCRIPTION
**Pull request by mkitti**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Addresses #118 

We previously only pinned suitesparse to 5.4.0 for host. This adds the suitesparse pin to 5.4.0 for run.

### CODE REVIEW

**Comment by izahn** [comment]
Why does `suitesparse` need to be pinned so hard?

**Comment by izahn** [comment]
Oh, I see https://github.com/conda-forge/julia-feedstock/issues/118

But can we make sure this is still a problem before pinning this so hard? I just installed `1.6.2` and installed Sundials without issue.

**Comment by mkitti** [comment]
Interesting. How does that work? I'll investigate.

**Comment by izahn** [comment]
I didn't look too closely, it just worked!

I also noticed that Archlinux maintains some patches, one of which replaces hard coded libraries: https://github.com/archlinux/svntogit-community/tree/packages/julia/trunk . Perhaps we can adapt that rather than pinning.

**Comment by mkitti** [comment]
The problem is not really Julia itself, but downstream packages which are expecting certain versions of libraries to be bundled with Julia.

I suppose from the conda-forge perspective, the solution would be to install Sundials_jll via conda-forge rather than from Julia's BinaryBuilder.

**Comment by izahn** [comment]
Yeah, I can see how that could be a problem. But is it actually? For example, can you currently reproduce https://github.com/conda-forge/julia-feedstock/issues/118 ?

**Comment by isuruf** [comment]
That error only happens if you use `Sundials_jll=5.2.0` With, `5.2.1` it is fixed.

**Comment by mkitti** [comment]
I thought Sundials_jll=5.2.1 was restricted to Julia 1.7?

**Comment by izahn** [comment]
I haven't kept up with changes to the julia packaging ecosystem in the last couple years, and it looks like things have changed a lot. The julia community has worked hard to build a packaging infrastructure that handles binary package dependencies. I think it's too bad they didn't join an existing effort instead, but they didn't.

Given the current situation I think the conda-forge community should think carefully about whether building julia and/or julia packages offers any real benefit. Perhaps we should just re-package upstream julia binaries and call it a day.

**Comment by mkitti** [comment]
> Perhaps we should just re-package upstream julia binaries and call it a day.

Viral Shah has suggested this in the past, and I recall it was met with pushback. The easier route for this would be just to install the official Julia binaries. However, I believe this conda-forge recipe in particular may offer some value.

The JLLs provide an override mechanism:
https://docs.binarybuilder.org/stable/building/#Overriding-a-prebuilt-JLL-package's-binaries

In that case, I believe it may be possible to override BinaryBuilder (BB) binaries with conda-forge ones if needed. I think this may be the best middle ground.

**Comment by izahn** [comment]
> Viral Shah has suggested this in the past, and I recall it was met with pushback. The easier route for this would be just  to install the official Julia binaries. However, I believe this conda-forge recipe in particular may offer some value.

Maybe, but it would be good if someone will articulate what that value is exactly. It is not currently obvious to me what the benefits are, other than perhaps some disk de-duplication.

> The JLLs provide an override mechanism:
> https://docs.binarybuilder.org/stable/building/#Overriding-a-prebuilt-JLL-package's-binaries
> 
> In that case, I believe it may be possible to override BinaryBuilder (BB) binaries with conda-forge ones if needed. I think this may be the best middle ground.

I read the documentation but I don't think that offers a viable way forward. The mechanism described there appears to be designed to help with julia package development, not to offer a way to use binaries installed by other systems. My strong impression is that BinaryBuilder is so baked in to julia package management that you can't really circumvent it.

**Comment by mkitti** [comment]
The overrides system is intended for package development and debugging, but it does offer a mechanism to use alternate shared or local libraries than the ones built by BinaryBuilder should that be needed. My understanding is that this mechanism has been used in the past in certain Linux distributions or by individuals to use local versions of binaries. Importantly, it provides a common and systematic mechanism to override. Perhaps we can get @giordano to comment when he returns from vacation.

Some individual Julia packages also provide a mechanism to point to local binaries than the BinaryBuilder JLLs. Julia's Pkg.jl still offers a mechanism to invoke a build step

I think the primary motivating factor for domesticating a JLL should be if incompatibilities arise.

Also note there is https://github.com/JuliaPy/Conda.jl which is a Julia package that wraps Conda, so in some cases it may be preferable to manage Julia in the same Conda environment. Given the issues on this repository, I think there is demand to install Julia via conda-forge. I've also heard from local colleagues that they would prefer to have a mechanism to install Julia via conda. 

For me personally, my motivation is that having Julia in conda-forge helps me to collaborate with others who prefer a conda-forge oriented workflow. It also widens the opportunities for Python-Julia interop, especially from a Python-centric perspective.

Overall, I agree that we should consider carefully how we are expending resources towards this effort.

**Comment by isuruf** [comment]
There are other issues than de-duplication of some files.
1. The platform support is slightly different. For eg: aarch64 binaries are made with glibc 2.19 instead of 2.17 that conda-forge uses.
2. When embedding julia with some other conda packages, the binaries would clash with each other.

**Pull request merged**
