### PR TITLE
fixing the curl issues

### PR DESCRIPTION
**Pull request by ngam**

### CODE REVIEW

**Comment by ngam** [comment]
@mkitti, they have weird hard-wiring in the checksums? i am not sure how best to handle this...

**Comment by ngam** [comment]
@mkitti, this should be good to go. Review and merge pls

**Comment by ngam** [comment]
@mkitti I have a question: After updating my conda env to this one; it all went well except in the "executing" part of updating it took forever. Then I forced it to stop (ctrl+c) and then it printed that it was recompiling the the julia project inside the conda env. Is that because we updated the Downloads.jl part or is this odd behavior?

I then started a new env (`conda create -n julia_test julia`) and everything was smooth and quick. So I guess it was the Downloads.jl update? Is it supposed to recompile/redownload everything?

**Comment by mkitti** [comment]
What is the "executing" part?

**Comment by ngam** [comment]
> What is the "executing" part?

Whenever you install/update a new package, you would get something like this at the end, see the "Executing transaction:"
```
Finished julia                                (00m:18s)             105 MB      5 MB/s
Downloading  [==================================================================] (00m:32s)    7.34 MB/s
Extracting   [==================================================================] (00m:32s)      15 / 15
Preparing transaction: done
Verifying transaction: done
Executing transaction: 

```

> Julia will attempt to precompile the environment so that packages load faster later. It sounds like it was slilently doing this. Is something suppressing the output?

Yes, that would be my guess too. It wasn't suppressed per se. Sometimes this part hangs and would appear later. 

> Did you have a lot of packages to compile in the environment that you updated? What did you update from? Were you changing minor versions?

I don't know what I had, but I think I was testing random things in it, so most likely I had a lot of random packages. I updated from an earlier 1.7.1 (_0) to the latest one 1.7.1 (_3).

---

My guess is that it is to do with Downloads.jl upgrade/change. Otherwise, this usually doesn't happen. For example, when I updated from 1.7.1 (_3) to 1.8.0 dev, it didn't pre/re compile things. I guess it would be interested to try it again by downgrading and see how that goes? I will try that now.

**Comment by ngam** [comment]
> > What is the "executing" part?
> 
> Whenever you install/update a new package, you would get something like this at the end, see the "Executing transaction:"
> 
> ```
> Finished julia                                (00m:18s)             105 MB      5 MB/s
> Downloading  [==================================================================] (00m:32s)    7.34 MB/s
> Extracting   [==================================================================] (00m:32s)      15 / 15
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: 
> ```
> 
>  > Julia will attempt to precompile the environment so that packages load faster later. It sounds like it was slilently doing this. Is something suppressing the output?
> 
> Yes, that would be my guess too. It wasn't suppressed per se. Sometimes this part hangs and would appear later.
> 
> > Did you have a lot of packages to compile in the environment that you updated? What did you update from? Were you changing minor versions?
> 
> I don't know what I had, but I think I was testing random things in it, so most likely I had a lot of random packages. I updated from an earlier 1.7.1 (_0) to the latest one 1.7.1 (_3).
> 
> My guess is that it is to do with Downloads.jl upgrade/change. Otherwise, this usually doesn't happen. For example, when I updated from 1.7.1 (_3) to 1.8.0 dev, it didn't pre/re compile things. I guess it would be interested to try it again by downgrading and see how that goes? I will try that now (update: ugh I can't really, we have a lot of broken stuff...)

**Comment by ngam** [comment]
> I will try that now

ugh... I can't really... we have a lot of broken stuff...

**Pull request merged**
