### PR TITLE
Pull pcre2 from conda-forge

### PR DESCRIPTION
**Pull request by dfornika**
Addresses #1.

### CODE REVIEW

**Comment by jakirkham** [comment]
Would raise this upstream and see if they have any suggestions.

**Comment by jakirkham** [comment]
Toggling for CIs.

**Comment by jakirkham** [comment]
Have you ever seen this error, @tkelman? Are there some other options we need to be using when building `pcre2`? 

```
LoadError("sysimg.jl",152,LoadError("show.jl",1238,ErrorException("PCRE JIT error: bad JIT option")))
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[2]: *** [/feedstock_root/build_artefacts/julia_1505267137273/work/julia-0.5.2/usr/lib/julia/sys.o] Error 1
make[1]: *** [julia-sysimg-release] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by jakirkham** [comment]
🎉

**Comment by dfornika** [comment]
I think we've got to bump the build number on this too. `0.5.2-1` was the build that removed the wrapper script, so this should be `0.5.2-2`

**Comment by jakirkham** [comment]
Right. Do you want to do this one?

**Pull request merged**
