### PR TITLE
Bump macOS SDK to 10.12 for codesign

### PR DESCRIPTION
**Pull request by mkitti**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mkitti** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
Why do you need 10.12 to codesign?

**Comment by mkitti** [comment]
> Why do you need 10.12 to codesign?

We're getting the following error in #229, so I'm trying this to see if this is indeed the issue.

```
Codesigning with identity -
Codesigning $PREFIX/lib/libjulia.1.8.dylib...
The following arguments were not expected: --deep --timestamp -vvv --option=runtime
```

See https://github.com/JuliaLang/julia/blob/master/contrib/codesign.sh

**Comment by mkitti** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
> Do you know what they use upstream?

https://twitter.com/vchuravy/status/1521963581180243969/photo/1

**Comment by mkitti** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
Isuru mentioned via gitter:

> we ship our own codesign binary that doesn't support all the ones that /usr/bin/codesign does. We already do codesigning in osx-arm64, so you don't need to do it yourself
> you can also delete the codesign binary in $BUILD_PREFIX/bin/codesign if you want

**Comment by mkitti** [comment]
I will probably defer this to #233

**Comment by mkitti** [comment]
I could not seem to figure out how to use the native codesign.

**Pull request closed without merging**
