### PR TITLE
 trying 1.8.0-beta1

### PR DESCRIPTION
**Pull request by ngam**
cc @mkitti  (we will probably want a RC/beta branch besides the dev branch)

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@mkitti this looks good to go more or less with the edits, so we should be ready for the 1.8 release. 

Only note: 

```
+ julia --project -e 'delete!(ENV, "JULIA_PROJECT"); delete!(ENV, "JULIA_LOAD_PATH"); Base.runtests(["loading", "cmdlineargs"])'
Test    (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
loading      (1) |        started at 2022-03-01T17:28:09.001
┌ Error: active project callback #19 failed
└ @ Base initdefs.jl:325
WARNING: replacing module Foo.
loading      (1) |    20.35 |   0.32 |  1.6 |    1875.15 |   372.36
cmdlineargs  (1) |        started at 2022-03-01T17:28:29.505

```

this is taking quite longer than I expected and I am not actually sure if it is passing with `Error: active project callback #19 failed` message... (it's still running)

**Comment by mkitti** [comment]
last time I looked into that error message, I think it was intentional...

**Comment by mkitti** [comment]
About `cmdlineargs`, let' see if osx has the same issue. I'll start asking upstream.

**Comment by ngam** [comment]
what would be connected to cmdlineargs in our config? I am not really sure... it's kinda weird. Hopefully it's just being slow...

**Comment by ngam** [comment]
blame: 
https://github.com/JuliaLang/julia/blame/master/test/cmdlineargs.jl

**Comment by mkitti** [comment]
I have no idea, but I do not see the same phenomenon in upstream CI:
https://build.julialang.org/#/builders/70/builds/2535/steps/5/logs/stdio

**Comment by ngam** [comment]
Okay, let's see if this concludes in time...

```
ERROR: Exception handler triggered on unmanaged thread.
ERROR: Exception handler triggered on unmanaged thread.
ERROR: Exception handler triggered on unmanaged thread.
ERROR: Exception handler triggered on unmanaged thread.
ERROR: Exception handler triggered on unmanaged thread.
threads                                  (1) |   337.23 |   0.05 |  0.0 |      60.96 |   324.48
stress                                   (1) |        started at 2022-03-01T18:13:33.757
(libuv) kqueue(): Too many open files

```

there was a recent libuv change upstream, so that might be something we could look into?

**Comment by ngam** [comment]
The OSX has just finished and passed

**Comment by ngam** [comment]
https://github.com/JuliaLang/julia/commit/ef3580460bbc67f1bee1871544bf7afc9691187f

**Comment by ngam** [comment]
Fyi: I just tested this locally on a linux64 machine and it passed. So this either is just stuck randomly or maybe it is hitting a CI memory limit or something. 

Anyway, I am going to run ALL tests next to see if we can have them all pass in a reasonable time...

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
this looks CI-related than julia-related to me... 

```
##[error]Exit code 137 returned from process: file name '/home/vsts/agents/2.200.2/externals/node10/bin/node', arguments '"/home/vsts/work/_tasks/CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9/2.198.0/cmdline.js"'.

```

**Comment by ngam** [comment]
But we have a problem on our hand with the CI (I believe it is a memory issue or something like that) for Linux64

**Comment by ngam** [comment]
@mkitti would something like `julia -e 'GC.gc()'` help at all? It seems to work fine if it is triggered all alone in [4bdc830](https://github.com/conda-forge/julia-feedstock/pull/197/commits/4bdc8303fe70cafea86487af85437a7484a4383d)

**Comment by ngam** [comment]
```
export PREFIX=/home/conda/feedstock_root/build_artifacts/julia_1646188240170/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/julia_1646188240170/test_tmp
+ julia -e 'using InteractiveUtils; InteractiveUtils.versioninfo()'
Julia Version 1.8.0-beta1
Commit 7b711ce699* (2022-02-23 15:09 UTC)
Platform Info:
  OS: Linux (x86_64-conda-linux-gnu)
  CPU: 2 × Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, haswell)
  Threads: 1 on 2 virtual cores
```

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@mkitti could you please take a moment to look at the error log here? I am not sure if we should take these errorshow and stacktraces failures seriously...

**Comment by mkitti** [comment]
Those errors suggest libunwind issues.

**Comment by mkitti** [comment]
Why did you change to libunwind 1.6? Julia still has not adopted the new ABI.

**Comment by ngam** [comment]
Was just testing. They changed to 1.5 recently, I thought some progress might have been made.

Are these issues similar to the ones from the past or are they different?

**Comment by mkitti** [comment]
They are exactly the ones from the past.

**Comment by ngam** [comment]
> They are exactly the ones from the past.

That's why I wanted to test it.

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
> @mkitti would something like `julia -e 'GC.gc()'` help at all? It seems to work fine if it is triggered all alone in [4bdc830](https://github.com/conda-forge/julia-feedstock/pull/197/commits/4bdc8303fe70cafea86487af85437a7484a4383d)

The GC should run itself. Perhaps there is a rogue process that has not exited or some open file handles that were not properly closed? What happens if we run these tests before the others.

**Comment by ngam** [comment]
Yeah, not really sure... Anyway, we should be able to push a 1.8 pretty quickly when it comes. This was just a test to see if we have everything in order. Closing.

**Pull request closed without merging**
