### PR TITLE
up to 1.7.0 (fixing patches)

### PR DESCRIPTION
**Pull request by ngam**
Also submitted julia to the osx-arm migrator 🤞 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please restart ci

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
I'll take a look this weekend.

**Comment by ngam** [comment]
> I'll take a look this weekend.

Thanks, it looks like it built correctly for osx, but it fails for linux for some reason.

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
Sorry the delay. I'm tracking to track down the libunwind issues before addressing Julia 1.7.

**Comment by ngam** [comment]
> Sorry the delay. I'm trying to track down the libunwind issues before addressing Julia 1.7.

No problem. I thought I would give it another try while you are addressing the libunwind :)

**Comment by ngam** [comment]
```
ERROR: LoadError: IOError: stream is closed or unusable
Stacktrace:
 [1] check_open
   @ ./stream.jl:386 [inlined]
 [2] uv_write_async(s::Base.TTY, p::Ptr{UInt8}, n::UInt64)
   @ Base ./stream.jl:1018
 [3] uv_write(s::Base.TTY, p::Ptr{UInt8}, n::UInt64)
   @ Base ./stream.jl:981
 [4] top-level scope
   @ ~/feedstock_root/build_artifacts/julia_1638922221723/work/contrib/generate_precompile.jl:416
 [5] eval(m::Module, e::Any)
   @ Core ./boot.jl:373
 [6] top-level scope
   @ ~/feedstock_root/build_artifacts/julia_1638922221723/work/contrib/generate_precompile.jl:6
in expression starting at /home/conda/feedstock_root/build_artifacts/julia_1638922221723/work/contrib/generate_precompile.jl:3
make[2]: *** [sysimage.mk:88: /home/conda/feedstock_root/build_artifacts/julia_1638922221723/work/usr/lib/julia/sys-o.a] Error 1
Generating REPL precompile statements... 26/36*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[1]: *** [Makefile:88: julia-sysimg-release] Error 2
make: *** [Makefile:47: /home/conda/feedstock_root/build_artifacts/julia_1638922221723/work/doc/_build/html/en/index.html] Error 2
make[2]: Leaving directory '$SRC_DIR'
make[1]: Leaving directory '$SRC_DIR'
Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 215, in main
    call_conda_build(action, config)
  File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 187, in call_conda_build
    result = api.build(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3083, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2206, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/julia_1638922221723/work/conda_build.sh']' returned non-zero exit status 2.
##[error]Bash exited with code '1'.

```

Any idea what this might be?

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
I think the libunwind issue is affecting Linux here as well. macOS uses a different library. To get things to work, we need to pin libunwind to version 1.5 or earlier. Mainstream Julia uses libunwind 1.3.2..

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
> 1.3.2

Should we do this exactly or should we do 1.5?

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
Closing this messy pr and will resume later when the pinning takes place.

**Pull request closed without merging**
