### PR TITLE
Test to see see if rebuild succeeds with libcurl 7.81.0-h494985f_0

### PR DESCRIPTION
**Pull request by mkitti**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mkitti** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
This build is using libcurl 7.81.0-h494985f_0. I am curious to see if it succeeds.

**Comment by mkitti** [comment]
@conda-forge-admin, please restart ci

**Comment by mkitti** [comment]
@conda-forge-admin, please restart ci

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@mkitti since curl has a global deps (see here: https://github.com/conda-forge/julia-feedstock/blob/master/.ci_support/linux_64_.yaml) you need to pin in it here: https://github.com/conda-forge/julia-feedstock/blob/master/recipe/conda_build_config.yaml

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
> This build is using libcurl 7.81.0-h494985f_0. I am curious to see if it succeeds.

Did it succeed? I can't see the logs

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
I don't really understand why this is failing where it is failing. We barely changed this recipe.

**Comment by ngam** [comment]
It's the intersection of curl and libigt2: 

https://github.com/conda-forge/libgit2-feedstock/blob/df856aa0a1cba23aea2d34142e3053311ab40003/recipe/meta.yaml#L30

**Comment by mkitti** [comment]
I see it now:
```
Generating REPL precompile statements... 25/36
#### inputting statement: ####
"Pkg.add(\"TestPkg\")"
####
Pkg.add("TestPkg")
julia> 
Pkg.add("TestPkg")

2004l   Resolving package versions...

signal (11): Segmentation fault
in expression starting at REPL[16]:1
Curl_connect at $PREFIX/lib/libcurl.so (unknown line)
multi_runsingle at $PREFIX/lib/libcurl.so (unknown line)
multi_socket at $PREFIX/lib/libcurl.so (unknown line)
curl_multi_socket_action at $PREFIX/lib/libcurl.so (unknown line)
curl_multi_socket_action at $SRC_DIR/usr/share/julia/stdlib/v1.7/LibCURL/src/lC_curl_h.jl:230 [inlined]
curl_multi_socket_action at $SRC_DIR/usr/share/julia/stdlib/v1.7/Downloads/src/Curl/utils.jl:91 [inlined]
macro expansion at $SRC_DIR/usr/share/julia/stdlib/v1.7/Downloads/src/Curl/utils.jl:35 [inlined]
```

**Comment by ngam** [comment]
Solution to this is to just turn libgit2 off for now.

**Comment by mkitti** [comment]
I just bisected the problem to https://github.com/curl/curl/commit/2b3dd01b779e4eff623a735792a915cde914b74a

**Comment by ngam** [comment]
Closing as we know the problem and potential solutions.

**Pull request closed without merging**
