### PR TITLE
V1.8.0-dev

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

---

Are these the legit options or are there more? https://github.com/JuliaLang/julia/blob/cd81054bae301ccf3a0fe7e0d8f60f167f1203a0/Makefile#L161-L222

```
# public libraries, that are installed in $(prefix)/lib
JL_TARGETS := julia
ifeq ($(BUNDLE_DEBUG_LIBS),1)
JL_TARGETS += julia-debug
endif

# private libraries, that are installed in $(prefix)/lib/julia
JL_PRIVATE_LIBS-0 := libccalltest libllvmcalltest libjulia-internal libjulia-codegen
ifeq ($(BUNDLE_DEBUG_LIBS),1)
JL_PRIVATE_LIBS-0 += libjulia-internal-debug libjulia-codegen-debug
endif
ifeq ($(USE_GPL_LIBS), 1)
JL_PRIVATE_LIBS-$(USE_SYSTEM_LIBSUITESPARSE) += libamd libbtf libcamd libccolamd libcholmod libcolamd libklu libldl librbio libspqr libsuitesparseconfig libumfpack
endif
JL_PRIVATE_LIBS-$(USE_SYSTEM_LIBBLASTRAMPOLINE) += libblastrampoline
JL_PRIVATE_LIBS-$(USE_SYSTEM_PCRE) += libpcre2-8
JL_PRIVATE_LIBS-$(USE_SYSTEM_DSFMT) += libdSFMT
JL_PRIVATE_LIBS-$(USE_SYSTEM_GMP) += libgmp libgmpxx
JL_PRIVATE_LIBS-$(USE_SYSTEM_MPFR) += libmpfr
JL_PRIVATE_LIBS-$(USE_SYSTEM_LIBSSH2) += libssh2
JL_PRIVATE_LIBS-$(USE_SYSTEM_NGHTTP2) += libnghttp2
JL_PRIVATE_LIBS-$(USE_SYSTEM_MBEDTLS) += libmbedtls libmbedcrypto libmbedx509
JL_PRIVATE_LIBS-$(USE_SYSTEM_CURL) += libcurl
JL_PRIVATE_LIBS-$(USE_SYSTEM_LIBGIT2) += libgit2
JL_PRIVATE_LIBS-$(USE_SYSTEM_LIBUV) += libuv
ifeq ($(OS),WINNT)
JL_PRIVATE_LIBS-$(USE_SYSTEM_ZLIB) += zlib
else
JL_PRIVATE_LIBS-$(USE_SYSTEM_ZLIB) += libz
endif
ifeq ($(USE_LLVM_SHLIB),1)
JL_PRIVATE_LIBS-$(USE_SYSTEM_LLVM) += libLLVM libLLVM-13jl
endif
JL_PRIVATE_LIBS-$(USE_SYSTEM_LIBUNWIND) += libunwind

ifeq ($(USE_SYSTEM_LIBM),0)
JL_PRIVATE_LIBS-$(USE_SYSTEM_OPENLIBM) += libopenlibm
endif

JL_PRIVATE_LIBS-$(USE_SYSTEM_BLAS) += $(LIBBLASNAME)
ifneq ($(LIBLAPACKNAME),$(LIBBLASNAME))
JL_PRIVATE_LIBS-$(USE_SYSTEM_LAPACK) += $(LIBLAPACKNAME)
endif

JL_PRIVATE_LIBS-$(USE_SYSTEM_CSL) += libgfortran libquadmath libstdc++ libgcc_s libgomp libssp libatomic
ifeq ($(OS),Darwin)
JL_PRIVATE_LIBS-$(USE_SYSTEM_CSL) += libc++
endif
ifeq ($(OS),WINNT)
JL_PRIVATE_LIBS-$(USE_SYSTEM_CSL) += libwinpthread
else
JL_PRIVATE_LIBS-$(USE_SYSTEM_CSL) += libpthread
endif


ifeq ($(OS),Darwin)
ifeq ($(USE_SYSTEM_BLAS),1)
ifeq ($(USE_SYSTEM_LAPACK),0)
JL_PRIVATE_LIBS-0 += libgfortblas
endif
endif
endif

```

---

```
export EXTRA_MAKEFLAGS="" 
if [[ "${target_platform}" == osx-* ]]; then
    export EXTRA_MAKEFLAGS="USE_SYSTEM_LIBGIT2=0 USE_SYSTEM_MBEDTLS=0"
elif [[ "${target_platform}" == linux-* ]]; then
    export EXTRA_MAKEFLAGS="USE_SYSTEM_LIBGIT2=1 USE_SYSTEM_MBEDTLS=1"
fi

...
# using system utf8proc can be enabled in 1.7.0. See https://github.com/JuliaLang/julia/commit/ba653ecb1c81f1465505c2cea38b4f8149dd20b3

make -j${CPU_COUNT} prefix=${PREFIX} sysconfigdir=${PREFIX}/etc \
 LIBBLAS=-lopenblas64_ LIBBLASNAME=libopenblas64_ LIBLAPACK=-lopenblas64_ LIBLAPACKNAME=libopenblas64_ \
 USE_SYSTEM_ARPACK=1 \
 USE_SYSTEM_BLAS=1 \
 USE_BLAS64=1 \
 USE_SYSTEM_CURL=1 \
 USE_SYSTEM_GMP=1 \
 USE_SYSTEM_LAPACK=1 \
 USE_SYSTEM_LIBSSH2=1 \
 USE_SYSTEM_LLVM=0 \
 USE_SYSTEM_MPFR=1 \
 USE_SYSTEM_OPENLIBM=1 \
 USE_SYSTEM_PATCHELF=1 \
 USE_SYSTEM_PCRE=1 \
 USE_SYSTEM_SUITESPARSE=1 \
 USE_SYSTEM_CSL=0 \
 USE_SYSTEM_LIBUNWIND=1 \
 USE_SYSTEM_LIBUV=0 \
 USE_SYSTEM_UTF8PROC=1 \
 USE_SYSTEM_NGHTTP2=1 \
 USE_SYSTEM_ZLIB=1 \
 USE_SYSTEM_P7ZIP=1 \
 ${EXTRA_MAKEFLAGS} \
 TAGGED_RELEASE_BANNER="https://github.com/conda-forge/julia-feedstock" \
 CC=$CC CXX=$CXX FC=$FC \
 install
```

### CODE REVIEW

**Comment by ngam** [comment]
@mkitti 

```
./version_git.jl
error during bootstrap:
LoadError(at "sysimg.jl" line 3: LoadError(at "Base.jl" line 158: LoadError(at "./version_git.jl" line 16: MethodError(f=Base.GitVersionInfo, args=("", "", "", 0, "", true, 0, 0), world=0x0000000000001e92))))

```

what is this?? lol

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
https://github.com/JuliaLang/julia/issues/43716

**Comment by mkitti** [comment]
I'm confused why this has not come up until now...

**Comment by mkitti** [comment]
Oh, because you switched to the tarballs...

**Comment by ngam** [comment]
> Oh, because you switched to the tarballs...

How would you have done it btw? Here, they really like tar balls, and it is easy to construct one from a commit --- so that's what I do...

**Comment by ngam** [comment]
Also, please provide feedback on the naming of the "version" --- we cannot have 1.8.0-DEV (cannot have dashes "-" in versions). So we could do just 1.8.0 or 1.8.0.dev or whatever you want...

**Comment by ngam** [comment]
Also, it seems that they might have some conventions upstream for the "nightly" builds? Looks like they're versioned like: `1.8.0-DEV.2000` --- do you know how that last number (2000) is decided?

Also, fyi:
```
+ julia --project -e 'delete!(ENV, "JULIA_PROJECT"); delete!(ENV, "JULIA_LOAD_PATH"); Base.runtests(["loading", "cmdlineargs"])'
Test    (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
loading      (1) |        started at 2022-01-09T03:05:45.486
┌ Error: active project callback #19 failed
└ @ Base initdefs.jl:325
WARNING: replacing module Foo.
loading      (1) |    25.39 |   0.39 |  1.5 |    2081.25 |   336.59
cmdlineargs  (1) |        started at 2022-01-09T03:06:11.072
cmdlineargs  (1) |   216.85 |   0.47 |  0.2 |     796.28 |   386.72

```

**Comment by mkitti** [comment]
If it's during testing, then I think one of those is expected:
https://github.com/JuliaLang/julia/blob/cd81054bae301ccf3a0fe7e0d8f60f167f1203a0/test/loading.jl#L229

**Comment by ngam** [comment]
Let's experiment with this here:

https://github.com/conda-forge/julia-feedstock/issues/172#issuecomment-1008225832

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
We should look into these two, I don't like em:

`LIBBLAS=-lopenblas64_ LIBBLASNAME=libopenblas64_ LIBLAPACK=-lopenblas64_ LIBLAPACKNAME=libopenblas64_ \`

**Comment by ngam** [comment]
a7a980f will likely break some stuff --- Let's go!!!

**Comment by ngam** [comment]
```
WARNING: Using boilerplate git version info
'$SRC_DIR/usr/bin/7z' -> '$PREFIX/bin/7z'
ln -sf $PREFIX/lib/libopenlibm.so.3 $SRC_DIR/usr/lib/julia/libopenlibm.so
ln -sf $PREFIX/lib/libpcre2-8.so.0 $SRC_DIR/usr/lib/julia/libpcre2-8.so
ln -sf $PREFIX/lib/libopenblas64_.so.0 $SRC_DIR/usr/lib/julia/libopenblas64_.so

100 20195  100 20195    0     0  58539      0 --:--:-- --:--:-- --:--:-- 58539
ln -sf $PREFIX/lib/libgmp.so.10 $SRC_DIR/usr/lib/julia/libgmp.so
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0ln -sf $PREFIX/lib/libmpfr.so.6 $SRC_DIR/usr/lib/julia/libmpfr.so
ln -sf $PREFIX/lib/libmbedtls.so.17 $SRC_DIR/usr/lib/julia/libmbedtls.so
ln -sf $PREFIX/lib/libmbedcrypto.so.11 $SRC_DIR/usr/lib/julia/libmbedcrypto.so
ln -sf $PREFIX/lib/libmbedx509.so.4 $SRC_DIR/usr/lib/julia/libmbedx509.so
ln -sf $PREFIX/lib/libssh2.so.1 $SRC_DIR/usr/lib/julia/libssh2.so
ln -sf $PREFIX/lib/libnghttp2.so.14 $SRC_DIR/usr/lib/julia/libnghttp2.so
ln -sf $PREFIX/lib/libcurl.so.4 $SRC_DIR/usr/lib/julia/libcurl.so
ln -sf $PREFIX/lib/libgit2.so.1.3 $SRC_DIR/usr/lib/julia/libgit2.so
ln -sf $PREFIX/lib/libamd.so.2 $SRC_DIR/usr/lib/julia/libamd.so
ln -sf $PREFIX/lib/libcamd.so.2 $SRC_DIR/usr/lib/julia/libcamd.so
ln -sf $PREFIX/lib/libccolamd.so.2 $SRC_DIR/usr/lib/julia/libccolamd.so
ln -sf $PREFIX/lib/libcholmod.so.3 $SRC_DIR/usr/lib/julia/libcholmod.so
ln -sf $PREFIX/lib/libcolamd.so.2 $SRC_DIR/usr/lib/julia/libcolamd.so
ln -sf $PREFIX/lib/libumfpack.so.5 $SRC_DIR/usr/lib/julia/libumfpack.so
ln -sf $PREFIX/lib/libspqr.so.2 $SRC_DIR/usr/lib/julia/libspqr.so
ln -sf $PREFIX/lib/libsuitesparseconfig.so.5 $SRC_DIR/usr/lib/julia/libsuitesparseconfig.so
make[2]: Leaving directory '$SRC_DIR/base'

```

**Comment by mkitti** [comment]
> Also, it seems that they might have some conventions upstream for the "nightly" builds? Looks like they're versioned like: `1.8.0-DEV.2000` --- do you know how that last number (2000) is decided?

https://github.com/JuliaLang/julia/blob/cd81054bae301ccf3a0fe7e0d8f60f167f1203a0/base/version_git.sh#L46-L53

**Comment by mkitti** [comment]
> We should look into these two, I don't like em:
> 
> `LIBBLAS=-lopenblas64_ LIBBLASNAME=libopenblas64_ LIBLAPACK=-lopenblas64_ LIBLAPACKNAME=libopenblas64_ \`

I'm pretty it was I who modified that line in #115

**Comment by ngam** [comment]
> > We should look into these two, I don't like em:
> > `LIBBLAS=-lopenblas64_ LIBBLASNAME=libopenblas64_ LIBLAPACK=-lopenblas64_ LIBLAPACKNAME=libopenblas64_ \`
> 
> I'm pretty it was I who modified that line in #115

Yeah, I know. I think I looked into this a little bit a while ago. Basically, we don't have those libraries otherwise... so we may need to push these feedstocks to standardize them or something.

**Comment by ngam** [comment]
We do have `lapack` for LIBLAPACK btw: https://anaconda.org/conda-forge/liblapack

**Comment by ngam** [comment]
So we may actually already have them.

**Comment by ngam** [comment]
```
bccalltest.so
    CC usr/lib/libllvmcalltest.so
Warning: git information unavailable; versioning information limited
Warning: git information unavailable; versioning information limited
Warning: git information unavailable; versioning information limited
$SRC_DIR/contrib/install.sh 755 $SRC_DIR/usr/bin/julia $PREFIX/bin/
for suffix in julia ; do \
	for lib in $SRC_DIR/usr/lib/lib${suffix}.*so*; do \
		if [ "${lib##*.}" != "dSYM" ]; then \
			$SRC_DIR/contrib/install.sh 755 $lib $PREFIX/lib ; \
		fi \
	done \
done
for suffix in libccalltest libllvmcalltest libjulia-internal libjulia-codegen libblastrampoline libdSFMT libuv libLLVM libLLVM-13jl libgfortran libquadmath libstdc++ libgcc_s libgomp libssp libatomic libpthread ; do \
	for lib in $SRC_DIR/usr/lib/${suffix}.*so*; do \
		if [ "${lib##*.}" != "dSYM" ]; then \
			$SRC_DIR/contrib/install.sh 755 $lib $PREFIX/lib/julia ; \
		fi \
	done \
done
cp: cannot stat '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/work/usr/lib/libpthread.*so*': No such file or directory
chmod: cannot access '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/julia/libpthread.*so*': No such file or directory
for suffix in libamd libbtf libcamd libccolamd libcholmod libcolamd libklu libldl librbio libspqr libsuitesparseconfig libumfpack libpcre2-8 libgmp libgmpxx libmpfr libssh2 libnghttp2 libmbedtls libmbedcrypto libmbedx509 libcurl libgit2 libz libunwind libopenlibm libopenblas64_ ; do \
	for lib in $SRC_DIR/usr/lib/julia/${suffix}.so*; do \
		if [ "${lib##*.}" != "dSYM" ]; then \
			$SRC_DIR/contrib/install.sh 755 $lib $PREFIX/lib/julia ; \
		fi \
	done \
done
cp: cannot stat '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/work/usr/lib/julia/libbtf.so*': No such file or directory
chmod: cannot access '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/julia/libbtf.so*': No such file or directory
cp: cannot stat '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/work/usr/lib/julia/libklu.so*': No such file or directory
chmod: cannot access '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/julia/libklu.so*': No such file or directory
cp: cannot stat '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/work/usr/lib/julia/libldl.so*': No such file or directory
chmod: cannot access '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/julia/libldl.so*': No such file or directory
cp: cannot stat '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/work/usr/lib/julia/librbio.so*': No such file or directory
chmod: cannot access '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/julia/librbio.so*': No such file or directory
cp: cannot stat '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/work/usr/lib/julia/libgmpxx.so*': No such file or directory
chmod: cannot access '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/julia/libgmpxx.so*': No such file or directory
cp: cannot stat '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/work/usr/lib/julia/libz.so*': No such file or directory
chmod: cannot access '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/julia/libz.so*': No such file or directory
cp: cannot stat '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/work/usr/lib/julia/libunwind.so*': No such file or directory
chmod: cannot access '/home/conda/feedstock_root/build_artifacts/julia_1641702575028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/julia/libunwind.so*': No such file or directory
# Install `7z` into libexec/
$SRC_DIR/contrib/install.sh 755 $SRC_DIR/usr/bin/7z $PREFIX/libexec/

```

**Comment by ngam** [comment]
@mkitti --- feel free to merge this whenever you want. Next steps (either in this PR or in future PRs):
1. use `USE_SYSTEM_CSL=1`
2. use `USE_SYSTEM_LIBUV=1`
3. investigate the archlinux patch: https://github.com/conda-forge/julia-feedstock/blob/dev/recipe/patches/julia-hardcoded-libs.patch (and modify if needed)
4. investigate some more loose ends like [this](https://github.com/conda-forge/julia-feedstock/pull/181#issuecomment-1008230667) and [this](https://github.com/conda-forge/julia-feedstock/issues/172#issuecomment-1008216618)  
5. think about LLVM
6. resolve osx: `EXTRA_MAKEFLAGS="USE_SYSTEM_LIBGIT2=0 USE_SYSTEM_MBEDTLS=0"`
6.

**Comment by mkitti** [comment]
Libuv will be difficult. I'm not sure if it is time yet.

Currently,  there is a Julia fork of libuv at
https://github.com/JuliaLang/libuv

Julia still communicates commits back to libuv proper but what Julia is using is actually their own fork.

My understanding is that the forks are closer than they have been in a while, but they are not the same.

The CSL thing should be fine, but there are likely additional binary compatability issues down that path.

**Comment by ngam** [comment]
What's the difference for julia between libblas and libopenblas?

**Comment by ngam** [comment]
> What's the difference for julia between libblas and libopenblas?

(fwiw: we can ship variants if needed...)

**Comment by ngam** [comment]
```
ln -sf $PREFIX/lib/libopenblas.so.0 $SRC_DIR/usr/lib/julia/libblas.so
ln -sf $PREFIX/lib/libopenblas.so.0 $SRC_DIR/usr/lib/julia/liblapack.so
```

**Comment by isuruf** [comment]
`openblas-ilp64` allows larger matrix sizes while `openblas` doesn't.

**Comment by ngam** [comment]
> openblas-ilp64 allows larger matrix sizes while openblas doesn't.

So... that sounds good, except it seems that ilp64 is only supported on linux64 and osx64, right? Should we downgrade for others?

**Comment by isuruf** [comment]
You can send a PR to support openblas-ilp64 variant for other architectures too.

**Comment by ngam** [comment]
> You can send a PR to support openblas-ilp64 variant for other architectures too.

Ah, okay perfect. Will do that soon. Alright, reverting these last two changes to go back to ilp64. Just saw this too: https://github.com/xianyi/OpenBLAS#supported-cpus-and-operating-systems

**Comment by ngam** [comment]
@mkitti happy to merge this or not yet?

**Comment by mkitti** [comment]
How does this work? If someone says `conda install -C conda-forge julia` in a new environment, will they get this release? Is there some special consideration for "dev" versions?

**Comment by isuruf** [comment]
See our docs on how to release dev versions to a separate channel.

**Comment by mkitti** [comment]
We need to modify recipe/conda_build_config.yaml don't we?

https://conda-forge.org/docs/maintainer/knowledge_base.html#knowledge-base

**Comment by ngam** [comment]
Already did: https://github.com/conda-forge/julia-feedstock/blob/dev/recipe/conda_build_config.yaml

**Comment by ngam** [comment]
Am I missing something?

**Comment by ngam** [comment]
> How does this work? If someone says `conda install -C conda-forge julia` in a new environment, will they get this release? Is there some special consideration for "dev" versions?

`conda install -c conda-forge/label/julia_dev -c conda-forge julia`

**Comment by ngam** [comment]
(I made the dev branch directly --- which is dumb, but oh well, the builds were broken, so it was okay --- and so this one is pushing onto the dev branch)

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by ngam** [comment]
@isuruf is here, so please ensure I am not doing something superbly dumb, thank you :)

**Comment by mkitti** [comment]
Did you want to use the dev number rather than a partial hash?

**Comment by ngam** [comment]
> Did you want to use the dev number rather than a partial hash?

I would love to reproduce their exact number, but I don't know how... I saw your link, but it made little sense to me :(

**Comment by ngam** [comment]
(No hurry to merge this btw --- I just want to make sure we are making progress on all these items, and it would be easier to disentangle them in separate PRs. We should also aim to release a new DEV version every week or so to preemptively test breaking changes in our deps, since we really cannot pin a max in practice)

**Comment by mkitti** [comment]
To get the build number, one would need to `git clone` the source tree and then do the following:

```
$ git checkout 5f6b8a1767f72c6b86ae391ece9c0ca52cd73c6b
HEAD is now at 5f6b8a1767 Generate memset and memmove intrinsics from ccalls (#43580)

$ make version_git.jl.phony
sh /home/mkitti/src/julia/base/version_git.sh /home/mkitti/src/julia/base > version_git.jl.phony
    PERL base/version_git.jl.phony

$ julia -E 'include("version_git.jl"); GIT_VERSION_INFO.build_number'
1258
```

**Comment by mkitti** [comment]
More directly, perhaps:

```
topdir=$(git rev-parse --show-toplevel)
verchanged=$(git blame -L ,1 -sl -- "$topdir/VERSION" | cut -f 1 -d " ")
git rev-list --count HEAD "^$verchanged"
```

**Comment by ngam** [comment]
sorry, for some reason the channel wasn't rendered correctly; I just rerendered and now it should be fine (pushed into dev directly). We may have one of 1.8.0.dev ones up there though... :(

**Comment by ngam** [comment]
my bad... https://anaconda.org/conda-forge/julia/files

**Comment by mkitti** [comment]
Umm, so how do we take it down?

**Comment by ngam** [comment]
PR to label mistake uplaods: https://github.com/conda-forge/admin-requests/pull/370

**Comment by ngam** [comment]
> Umm, so how do we take it down?

All clear --- the two files shouldn't be available for downlaod. Ouuf.

**Pull request merged**
