### PR TITLE
V0.6.1

### PR DESCRIPTION
**Pull request by dfornika**
Addresses #37.

### CODE REVIEW

**Comment by dfornika** [comment]
Does anyone have opposition to merging this?

**Comment by jakirkham** [comment]
The diff seems fine, but I'm having trouble following the commit history. Why is the macOS branch merged in here and seemingly reverted?

**Comment by dfornika** [comment]
@jakirkham I don't know, I didn't do that on purpose. I just created a new branch from my `julia-feedstock` repo and made the most recent few commits.

Should I create a new pull request with a cleaner commit history?

**Comment by jakirkham** [comment]
I see. That's probably a good idea. Otherwise merging this might close the macOS PR.

**Pull request closed without merging**
