### PR TITLE
Revert "julia v1.7.2 (#188)"

### PR DESCRIPTION
**Pull request by ngam**
This reverts commit bff8dfff5f1dc92292789fb853cfd69c0da8f347.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@mkitti, let's start from where we were before this error. Let's do this step by step and figure out where things are failing (likely patches)

**Comment by mkitti** [comment]
We want to remove this one: 0001-disable-testing-Vararg-Int-N-where.patch.native

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by mkitti** [comment]
Here's the error we were getting.
```
Applying patch: /home/conda/recipe_root/patches/0001-disable-testing-Vararg-Int-N-where.patch
Applying patch: /home/conda/recipe_root/patches/0001-disable-testing-Vararg-Int-N-where.patch with args:
['-Np1', '-i', '/tmp/tmppil58e59/0001-disable-testing-Vararg-Int-N-where.patch.native', '--binary']
checking file test/core.jl
Hunk #1 FAILED at 3516.
1 out of 1 hunk FAILED
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/opt/conda/bin/patch', '--no-backup-if-mismatch', '--batch', '-Np1', '-i', '/tmp/tmppil58e59/0001-disable-testing-Vararg-Int-N-where.patch.native', '--binary', '--dry-run']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 239, in main
    call_conda_build(action, config)
  File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 211, in call_conda_build
    result = api.build(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 3088, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 2138, in build
    try_download(m, no_download_source=False, raise_error=True)
  File "/opt/conda/lib/python3.9/site-packages/conda_build/render.py", line 662, in try_download
    raise RuntimeError("Failed to download or patch source. Please see build log for info.")
RuntimeError: Failed to download or patch source. Please see build log for info.
##[error]Bash exited with code '1'.
```

**Comment by ngam** [comment]
The ci failures are likely this patch. They only fixed that in 1.8.x, I think?

```
## fix the curl issues:
     ## see: https://github.com/JuliaLang/Downloads.jl/issues/172
     - patches/0001-upgrading-downloads-v1.7.1.patch
```

**Comment by ngam** [comment]
Hey, at least they're consistent :)

**Comment by ngam** [comment]
Okay, once these pass (I am also running stuff locally) we can more methodically pick the changes we need from other PR. Could we test the CondaPkg.jl integration or should we address that in another PR?

**Comment by mkitti** [comment]
This one needs to go as well patches/0003-correct-test-for-julia-depot-path

**Comment by mkitti** [comment]
Another PR. The CondaPkg.jl change has not even been released.

**Comment by ngam** [comment]
@mkitti, I think this is it --- all changes from the dev branch except the patches

**Comment by mkitti** [comment]
Looks good to me.

We may need to do some work on the 1.6 branch later.

**Comment by ngam** [comment]
> Looks good to me.
> 
> We may need to do some work on the 1.6 branch later.

Forgot about that --- did they have a new release?

**Comment by mkitti** [comment]
Thr latest is 1.6.5, but I see a 1.6.6 coming.

**Pull request merged**
