### PR TITLE
USE_SYSTEM_CSL=1

### PR DESCRIPTION
**Pull request by mkitti**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
This seems likely failing because we are still using MBEDTLS and LIBGIT2 vendored for osx

**Comment by mkitti** [comment]
Where do you see that?

It looks to me that things are messed up here:
```
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `if [ -e "failed to open library: dlopen(libssp.0.dylib, 1): image not found" ]; then REALPATH=failed to open library: dlopen(libssp.0.dylib, 1): image not found; REALPATH_wd="`pwd`" && REALPATH_=`readlink -n ${REALPATH} || true` && if [ -n "${REALPATH_}" ]; then REALPATH_wd=`dirname "${REALPATH}"`; REALPATH="${REALPATH_}"; fi && if [ -z "`echo ${REALPATH} | grep '^/'`" ]; then REALPATH=${REALPATH_wd}/${REALPATH}; fi && REALPATH_=`otool -D ${REALPATH} | tail -n +2 | sed -e 's/^@.*$//'` && if [ -n "${REALPATH_}" ]; then REALPATH_wd=`dirname "${REALPATH}"`; REALPATH=${REALPATH_}; if [ -z "`echo ${REALPATH} | grep '^/'`" ]; then REALPATH=${REALPATH_wd}/${REALPATH}; fi; fi && [ -e "$REALPATH" ] && ([ ! -e "/Users/runner/miniforge3/conda-bld/julia_1642336878236/work/usr/lib/julia/libssp.0.dylib" ] || rm "/Users/runner/miniforge3/conda-bld/julia_1642336878236/work/usr/lib/julia/libssp.0.dylib") && echo ln -sf "$REALPATH" "/Users/runner/miniforge3/conda-bld/julia_1642336878236/work/usr/lib/julia/libssp.0.dylib" && ln -sf "$REALPATH" "/Users/runner/miniforge3/conda-bld/julia_1642336878236/work/usr/lib/julia/libssp.0.dylib"; else if [ "ALLOW_FAILURE" != "ALLOW_FAILURE" ]; then echo "System library symlink failure: Unable to locate libssp.0.dylib on your system!" >&2; false; fi; fi'
```

What is `libssp`? https://reviews.freebsd.org/D15687 It's a `gcc` library. At the moment we're compiling with `clang`.

**Comment by ngam** [comment]
What does `USE_SYSTEM_CSL=1` actually do?

**Comment by ngam** [comment]
I do think you're right though

**Comment by mkitti** [comment]
CSL stands for C(++) Standard Library. It refers to

libgfortran
libquadmath
libstdc++
libc++
libgcc_s
libssp
libpthread
libwinpthread
libatomic
libgomp

https://github.com/JuliaLang/julia/blob/master/deps/csl.mk

**Comment by mkitti** [comment]
The default is to disable this if the system libraries are new enough:
https://github.com/JuliaLang/julia/blob/352266160f14d9d0fcfc3552c6f83f86d9bd4944/deps/csl.mk#L35-L40

**Comment by mkitti** [comment]
Correction, it stands for Compiler Support Libraries:
https://github.com/JuliaPackaging/Yggdrasil/blob/master/C/CompilerSupportLibraries/build_tarballs.jl

**Comment by mkitti** [comment]
Based on these lines, I'm thinking that we should not do this.

There is already logic there to enable and disable this depending on the compiler and if the existing libraries are new enough.

https://github.com/JuliaLang/julia/blob/352266160f14d9d0fcfc3552c6f83f86d9bd4944/deps/csl.mk#L28-L48

```
ifeq ($(USE_BINARYBUILDER),0)
USE_BINARYBUILDER_CSL ?= 0
else
# If it's not, check to see if it's disabled by a USE_SYSTEM_xxx flag
ifeq ($(USE_SYSTEM_CSL),1)
USE_BINARYBUILDER_CSL ?= 0
else
# If it's not, see if we should disable it due to `libstdc++` being newer:
LIBSTDCXX_PATH := $(eval $(call pathsearch,libstdc++,$(STD_LIB_PATH)))
ifneq (,$(and $(LIBSTDCXX_PATH),$(shell objdump -p $(LIBSTDCXX_PATH) | grep $(CSL_NEXT_GLIBCXX_VERSION))))
# Found `libstdc++`, grepped it for strings and found a `GLIBCXX` symbol
# that is newer that whatever we have in CSL.  Default to not using BB.
USE_BINARYBUILDER_CSL ?= 0
else
# Either we didn't find `libstdc++` (e.g. we're using `clang`), or we
# found it and couldn't find the new symbol in it (it's older than what
# BB provides, so let's use BB instead)
USE_BINARYBUILDER_CSL ?= 1
endif
endif
endif
```

**Comment by mkitti** [comment]
Could you figure out how to add a GNU/gcc toolchain on macOS?

**Comment by ngam** [comment]
> Based on these lines, I'm thinking that we should not do this.

I agree

> Could you figure out how to add a GNU/gcc toolchain on macOS?

I think that would mess up more than we want to achieve here... and I don't know how. I tried looking into all the compilers available and I couldn't find libssp

**Comment by mkitti** [comment]
I'm asking https://gitter.im/conda-forge/conda-forge.github.io if they know anything about libssp on macOS

**Comment by ngam** [comment]
@mkitti re 2990f40, nothing provides `gcc` for osx; I checked locally. You can try `mamba/conda install compilers` locally and see if you can find anything --- I did and I couldn't. I generally agree that we can drop this for now --- it really doesn't seem like worth it after looking through csl.mk, etc.

**Comment by ngam** [comment]
> I'm asking https://gitter.im/conda-forge/conda-forge.github.io if they know anything about libssp on macOS

That's the quickest way to get answers, but I never signed up for that. Let me know if you need help in the woflv's suggestion to submit a staged-recipes; I can do that later this week for you (it's relatively straightforward)

**Comment by ngam** [comment]
> I did and I couldn't

I did find online someone saying you can get it under `x86_64-apple-darwin13.4.0-...`, but I couldn't find it after installing a lot of random pieces where it could reside

**Comment by ngam** [comment]
If you are going to do a staged-recipes, you might as well just a do the whole gcc for osx --- but you should consult with them more because that's obviously a big piece of work

**Comment by mkitti** [comment]
Yea, `gcc` is more than I think I can handle without having any actual Apple hardware in front of me.

**Comment by ngam** [comment]
> Yea, `gcc` is more than I think I can handle without having any actual Apple hardware in front of me.

I have a lot of Apple hardware around, so I can help if needed. But I just don't think `USE_SYSTEM_CSL` is worth it for now. We can put our energy into MBEDTLS and LIBGIT2 instead... for starters

**Comment by ngam** [comment]
@mkitti @isuruf @beckermr @wolfv: this does have libssp (and all the CSL stuff)

https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/12.0.0-20211211-experimental

Is this the one we are building in conda-forge?

**Comment by ngam** [comment]
(I am NOT recommending that we do --- just pointing this out. I also don't think we should do the CSL stuff for Julia as discussed above)

**Comment by mkitti** [comment]
We do have https://anaconda.org/conda-forge/gfortran_osx-64

**Comment by ngam** [comment]
> We do have https://anaconda.org/conda-forge/gfortran_osx-64

Doesn't actually have... the one I linked is more like the full gcc stuff

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
Closing this for now as moving to system CSL is not feasible at this point.

**Pull request closed without merging**
