### PR TITLE
testing the pins

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@mkitti just testing and playing around here, hope you don't mind. I also wonder if we need to add something in conda-forge.yml or something like that...

**Comment by ngam** [comment]
still
 
```
    libunwind:         1.6.2-h9c3ff4c_0           conda-forge
```

but going much farther than the previous build... not sure why

**Comment by mkitti** [comment]
I appreciate the attempt. Thanks.

**Comment by ngam** [comment]
@mkitti fails deep in testing locally, any idea why?

```
    errorshow         |      212     4      2               218
    stacktraces       |       40     8                       48
```

Full summary:

```
Test Summary:         |     Pass  Fail  Error  Broken     Total
  Overall             | 28835685    12      2  352569  29188268
    compiler/validation |       26                             26
    compiler/irpasses |       22                             22
    compiler/ssair    |       39                             39
    compiler/inline   |       42                    1        43
    compiler/contextual |        6                              6
    compiler/codegen  |      145                            145
    ambiguous         |      101                    2       103
    strings/search    |      692                            692
    compiler/inference |      893                    1       894
    strings/basic     |    87674                          87674
    strings/io        |    12751                          12751
    unicode/utf8      |       19                             19
    strings/util      |      461                            461
    worlds            |       83                             83
    strings/types     |  2302691                        2302691
    keywordargs       |      151                            151
    subtype           |   337653                   16    337669
    char              |     1529                           1529
    triplequote       |       29                             29
    intrinsics        |       90                             90
    core              |  8445874                    4   8445878
    dict              |   144409                         144409
    iobuffer          |      204                            204
    staged            |       64                             64
    numbers           |  1578564                    1   1578565
    hashing           |    12356                          12356
    tuple             |      578                            578
    reduce            |     8545                           8545
    offsetarray       |      477                    3       480
    reducedim         |      817                            817
    intfuncs          |   215864                         215864
    simdloop          |      249                            249
    vecelement        |      678                            678
    arrayops          |     1979                    2      1981
    abstractarray     |    55818                24795     80613
    subarray          |   318299                         318299
    copy              |      532                            532
    rational          |    98622                    1     98623
    functional        |       95                             95
    fastmath          |      934                            934
    ordering          |       35                             35
    path              |      357                   12       369
    operators         |    12949                          12949
    parse             |    16098                          16098
    loading           |   143344                         143344
    gmp               |     2315                           2315
    ccall             |     5332                           5332
    iterators         |    10071                          10071
    backtrace         |       35                    1        36
    spawn             |      206                    4       210
    exceptions        |       70                             70
    file              |     1038                           1038
    version           |     2452                           2452
    namedtuple        |      194                    1       195
    read              |     3143                           3143
    mpfr              |     1135                           1135
    complex           |     8429                    5      8434
    floatapprox       |       49                             49
    sorting           |    12709                   10     12719
    reflection        |      403                            403
    regex             |      114                            114
    float16           |      235                            235
    sysinfo           |        4                              4
    env               |      131                            131
    combinatorics     |      170                            170
    rounding          |   112720                         112720
    mod2pi            |       80                             80
    euler             |       12                             12
    broadcast         |      480                            480
    client            |        3                              3
    ranges            | 12109815               327693  12437508
    show              |     1520                    8      1528
    goto              |       19                             19
    llvmcall          |       19                             19
    llvmcall2         |        7                              7
    ryu               |    31215                          31215
    some              |       65                             65
    meta              |       64                             64
    errorshow         |      212     4      2               218
    stacktraces       |       40     8                       48
    docs              |      227                            227
    binaryplatforms   |      341                            341
    sets              |     3518                    1      3519
    atexit            |       40                             40
    enums             |       99                             99
    misc              |  1282109                        1282109
    interpreter       |        3                              3
    int               |   524668                         524668
    bitset            |      195                            195
    checked           |     1239                           1239
    boundscheck       |                                No tests
    error             |       31                             31
    cartesian         |      234                    3       237
    osutils           |       42                             42
    channels          |      237                            237
    iostream          |       50                             50
    secretbuffer      |       27                             27
    specificity       |      175                            175
    reinterpretarray  |      226                            226
    syntax            |     1406                    1      1407
    corelogging       |      231                            231
    missing           |      472                    1       473
    asyncmap          |      292                            292
    smallarrayshrink  |       36                             36
    floatfuncs        |      193                            193
    download          |                                No tests
    cmdlineargs       |      245                    3       248
    bitarray          |   911770                         911770
    precompile        |      116                            116
    threads           |        1                              1
    stress            |      118                            118
    FAILURE

```

**Comment by mkitti** [comment]
What version of libunwind do you have locally? libunwind is used for showing errors and stacktraces..

**Comment by ngam** [comment]
Closing, I don't think I have a solution.

**Comment by ngam** [comment]
> What version of libunwind do you have locally? libunwind is used for showing errors and stacktraces..

with that error, it was 1.6.2. Now, it is building with 1.5.0 (you can also track the ci here, though it is slow)

**Comment by ngam** [comment]
It's weird because this is exactly the same as yours. I made my edits and then reverted back to your PR, and now it is 1.5.0 and I have no idea why it is refusing to rerender on the other PR

**Comment by ngam** [comment]
ugh... the host seems to be the only one 1.5.0

the run one is 1.6.2

```
    gmp:               6.2.1-h58526e2_0           conda-forge
    julia:             1.6.4-h989b2f6_2           local      
    krb5:              1.19.2-h48eae69_3          conda-forge
    libblas:           3.9.0-12_linux64_openblas  conda-forge
    libcblas:          3.9.0-12_linux64_openblas  conda-forge
    libcurl:           7.80.0-h494985f_1          conda-forge
    libedit:           3.1.20191231-he28a2e2_2    conda-forge
    libev:             4.33-h516909a_1            conda-forge
    libffi:            3.4.2-h7f98852_5           conda-forge
    libgcc-ng:         11.2.0-h1d223b6_11         conda-forge
    libgfortran-ng:    11.2.0-h69a702a_11         conda-forge
    libgfortran5:      11.2.0-h5c6108e_11         conda-forge
    libgit2:           1.3.0-haabb1ae_1           conda-forge
    libgomp:           11.2.0-h1d223b6_11         conda-forge
    libiconv:          1.16-h516909a_0            conda-forge
    liblapack:         3.9.0-12_linux64_openblas  conda-forge
    libnghttp2:        1.43.0-ha19adfc_1          conda-forge
    libopenblas:       0.3.18-pthreads_h8fe5266_0 conda-forge
    libopenblas-ilp64: 0.3.18-pthreads_h0aa5bea_0 conda-forge
    libssh2:           1.10.0-ha35d2d1_2          conda-forge
    libstdcxx-ng:      11.2.0-he4da1e4_11         conda-forge
    libunwind:         1.6.2-h9c3ff4c_0           conda-forge

```

**Comment by ngam** [comment]
Ugh, my git commit didn't include the most important piece, the conda_build_config.yaml whose contents are below. It's okay though, I will add it once the ci concludes (its effect is already committed via rerendering)

```yaml
libunwind:  # [linux]
  - 1.5  # [linux]
pin_run_as_build:  # [linux]
    libunwind:  # [linux]
      max_pin: x.x  # [linux]
```

**Comment by ngam** [comment]
@mkitti I think we are good to go, didn't fail on previous errors. I am going to recommit everything, add myself as a maintainer (I am interested in pushing osxarm64) and we can work together to push up all releases


```
stress               (1) |    22.23 |   0.04 |  0.2 |     108.12 |   312.82

Test Summary: |     Pass  Broken     Total
  Overall     | 28857782  352569  29210351
    SUCCESS
+ julia -e 'Base.runtests(["math"])'
Test  (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)

```

**Comment by ngam** [comment]
```
Precompiling project...
  91 dependencies successfully precompiled in 107 seconds (2 already precompiled)
+ exit 0

Resource usage statistics from testing julia:
   Process count: 18
   CPU time: Sys=0:02:18.9, User=0:50:20.5
   Memory: 5.4G
   Disk usage: 20B
   Time elapsed: 0:18:37.2
```

**Comment by ngam** [comment]
note libunwind!

```
INFO :: The inputs making up the hashes for the built packages are as follows:
{
  "julia-1.6.4-h989b2f6_2": {
    "recipe": {
      "arpack": "3.7",
      "c_compiler": "gcc",
      "c_compiler_version": "9",
      "channel_targets": "conda-forge main",
      "curl": "7",
      "cxx_compiler": "gxx",
      "cxx_compiler_version": "9",
      "fortran_compiler": "gfortran",
      "fortran_compiler_version": "9",
      "gmp": "6",
      "libgit2": "1.3",
      "libssh2": "1",
      "libunwind": "1.5",
      "mpfr": "4",
      "pcre2": "10.37",
      "suitesparse": "5",
      "target_platform": "linux-64",
      "zlib": "1.2"
    }
  }
}


```

**Comment by ngam** [comment]
@mkitti all green

**Comment by ngam** [comment]
are you okay to merge this or is there something else?

**Comment by mkitti** [comment]
This looks good. I just wanted to look it over carefully before merging.

**Comment by mkitti** [comment]
> I am interested in pushing osxarm64

Note that this should be done with Julia 1.7, which should follow shortly once we get this working.

**Comment by mkitti** [comment]
My main question is what is actually the minimum number changes needed to get everything working. I am not sure if it is worth getting the answer.

**Comment by ngam** [comment]
> My main question is what is actually the minimum number changes needed to get everything working. I am not sure if it is worth getting the answer.

For now, adding conda_build_config.yaml in the recipe directory with this the following content:

```yaml
libunwind:  # [linux]
  - 1.5  # [linux]
pin_run_as_build:  # [linux]
    libunwind:  # [linux]
      max_pin: x.x  # [linux]
```

They may set `pin_run_as_build` as default in future iterations, but for now, I think this is your best bet. Otherwise, you will be waiting for weeks. Remember, you can always change things for future versions. And yes, we should get both the 1.7 version done as well as a LTS branch.

**Comment by ngam** [comment]
> > My main question is what is actually the minimum number changes needed to get everything working. I am not sure if it is worth getting the answer.
> 
> For now, adding conda_build_config.yaml

And this is the "proper" solution. As you know, you can manually set the version of libunwind if you want, but that would be "improper" according to the docs...

**Comment by ngam** [comment]
Anyway, a further fix to the pinning will need some of the more knowledgeable people to get involved.

**Comment by ngam** [comment]
> This looks good. I just wanted to look it over carefully before merging.

Yes, please look carefully. To get from your PR to this, you just need to add the file and then rerender. That's all. Nothing else. All other edits are automated.

**Comment by mkitti** [comment]
Thanks for the explanation. Let's move forward.

**Pull request merged**
