### PR TITLE
Bump to 1.8.0.dev.1261, remove merged patches

### PR DESCRIPTION
**Pull request by mkitti**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mkitti** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
thanks @mkitti and sorry about the mistake in the other PR

**Review by ngam — APPROVED** [review]

**Comment by ngam** [comment]
> thanks @mkitti and sorry about the mistake in the other PR

Could you please make sure you're starting from the most recent dev branch? This commit: https://github.com/conda-forge/julia-feedstock/commit/cccbcddc5228c33b7b121910fbbb018e11e53470

**Comment by ngam** [comment]
fyi, this is how the version looks like:

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV
 _/ |\__'_|_|_|\__'_|  |  https://github.com/conda-forge/julia-feedstock
|__/                   |

```

**Comment by mkitti** [comment]
> > thanks @mkitti and sorry about the mistake in the other PR
> 
> Could you please make sure you're starting from the most recent dev branch? This commit: https://github.com/conda-forge/julia-feedstock/commit/cccbcddc5228c33b7b121910fbbb018e11e53470

I'm pretty sure that is what dd37edc5b5aef6edfb024f52acd631d9517df5ac is

**Comment by mkitti** [comment]
> fyi, this is how the version looks like:
> 
> ```
>                _
>    _       _ _(_)_     |  Documentation: https://docs.julialang.org
>   (_)     | (_) (_)    |
>    _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
>   | | | | | | |/ _` |  |
>   | | |_| | | | (_| |  |  Version 1.8.0-DEV
>  _/ |\__'_|_|_|\__'_|  |  https://github.com/conda-forge/julia-feedstock
> |__/                   |
> 
> ```
> 
> Maybe we could echo the version number in the version file?
> 
> Also look at these details and let me know if details under "Environment" are exactly as expected. I thought we set the certificate differently --- basically I am not sure if last four variables are correct... 
> 
> I am still a bit surprised this build isn't taking up their styling like `Julia Version 1.8.0-DEV.1258`
> 
> ```
> 
> ~$ julia
>                _
>    _       _ _(_)_     |  Documentation: https://docs.julialang.org
>   (_)     | (_) (_)    |
>    _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
>   | | | | | | |/ _` |  |
>   | | |_| | | | (_| |  |  Version 1.8.0-DEV
>  _/ |\__'_|_|_|\__'_|  |  https://github.com/conda-forge/julia-feedstock
> |__/                   |
> 
> julia> versioninfo()
> Julia Version 1.8.0-DEV
> Platform Info:
>   OS: macOS (x86_64-apple-darwin13.4.0)
>   CPU: Apple M1 Max
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-13.0.0 (ORCJIT, westmere)
> Environment:
>   JULIA_DEPOT_PATH_BACKUP = 
>   JULIA_PROJECT_BACKUP = 
>   JULIA_LOAD_PATH_BACKUP = 
>   JULIA_DEPOT_PATH = /Users/ngam/.Mambaforge-MacOSX-x86_64/envs/jlia/share/julia:
>   JULIA_PROJECT = @jlia
>   JULIA_LOAD_PATH = @:@jlia:@stdlib
>   JULIA_SSL_CA_ROOTS_PATH_BACKUP = 
>   JULIA_SSL_CA_ROOTS_PATH = /Users/ngam/.Mambaforge-MacOSX-x86_64/envs/jlia/ssl/cacert.pem
> 
> julia> 
> 
> 
> ```

We are not building from a git repository, so version_git.sh cannot do it's job of generating version_git.jl.

**Comment by ngam** [comment]
> git repository

Ah! Do you want us to try to build from the git repo directly here? I don't think they (the core) like this, but since it is dev, it might be okay... Up to you to experiment. https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos

**Comment by ngam** [comment]
Do you want me to merge or would you like to add more to this PR?

**Comment by mkitti** [comment]
For the dev builds, we probably should just build from git.

**Review by ngam — APPROVED** [review]

**Comment by ngam** [comment]
Merging, let's goooooooo!

**Comment by ngam** [comment]
> For the dev builds, we probably should just build from git.

Sure, if we get complaints, we can reverse course, but for now this is good for me!

**Comment by mkitti** [comment]
That's the date of https://github.com/conda-forge/julia-feedstock/blob/41be9d1aa4fb8e48fd7e367a781a95dea076e222/recipe/patches/julia-hardcoded-libs.patch#L3

**Pull request merged**
