### PR TITLE
Release 0.6.0

### PR DESCRIPTION
**Pull request by dfornika**
Addresses #6.

### CODE REVIEW

**Comment by jakirkham** [comment]
Would suggest raising this test failure upstream and seeing what they say.

**Comment by dfornika** [comment]
I will. This sort of issue belongs on the Julia 'discourse' list, not an issue on the julia Github repo, correct? Or is there another place to discuss this?

**Comment by jakirkham** [comment]
It seems like a build issue. So personally would add it to the issue tracker, but will happily defer to your judgement on where to raise it.

**Comment by dfornika** [comment]
Ok, I've posted it to the julia discourse for now. Will create a github issue if it doesn't get any attention there.

https://discourse.julialang.org/t/test-spawn-failure-in-conda-build-julia-0-6-0/

**Comment by tkelman** [comment]
Your llvm build is the wrong version or insufficiently patched. Anything that can't be reproduced with the official binaries or recommended build configuration would be closed as a packaging bug.

**Comment by jakirkham** [comment]
We aren't using the `conda-forge` packaged LLVM though. We are just using the one that Julia builds itself. 😕

**Comment by tkelman** [comment]
Does the failure happen if you drop the wrapper script business?

**Comment by jakirkham** [comment]
I've raised issue ( https://github.com/conda-forge/julia-feedstock/issues/10 ) in regards to removing the wrapper script. However I'm not entirely sure it is possible to remove the wrappers script as noted in that issue.

**Comment by dfornika** [comment]
I've set up a pull request against the `v0.5` branch to remove the wrapper script (just got it started, not sure how to configure the `.juliarc` right now).

**Comment by jakirkham** [comment]
Toggling for CIs.

**Comment by dfornika** [comment]
```
Worker 1 failed running test spawn:
Some tests did not pass: 106 passed, 1 failed, 0 errored, 4 broken.spawn: Test Failed
  Expression: readchomp(pipeline(ignorestatus(@cmd("\$exename --startup-file=no -e '\n            struct Error19864 <: Exception; end\n            Base.showerror(io::IO, e::Error19864) = print(io, \"correct19864\")\n            throw(Error19864())'")), stderr=catcmd)) == "ERROR: correct19864"
   Evaluated: "warning: parsing line table prologue at 0x0001bb18 should have ended at 0x0001beac but it ended at 0x0001bbf7\nwarning: parsing line table prologue at 0x0000be03 should have ended at 0x0000c16a but it ended at 0x0000bed5\nwarning: parsing line table prologue at 0x000074a3 should have ended at 0x0000786e but it ended at 0x000075c6\nwarning: parsing line table prologue at 0x00002673 should have ended at 0x00002a48 but it ended at 0x00002745\nwarning: parsing line table prologue at 0x000095e1 should have ended at 0x00009909 but it ended at 0x000096b3\nwarning: parsing line table prologue at 0x000112ea should have ended at 0x0001166e but it ended at 0x000113bc\nwarning: parsing line table prologue at 0x00000000 should have ended at 0x00000434 but it ended at 0x00000167\nERROR: correct19864" == "ERROR: correct19864"warning: parsing line table prologue at 0x00000000 should have ended at 0x00000434 but it ended at 0x00000167

Stacktrace:
 [1] record(::Base.Test.DefaultTestSet, ::Base.Test.Fail) at ./test.jl:568
 [2] (::##40#46)() at /feedstock_root/build_artefacts/julia_1505088090973/_t_env/share/julia/test/runtests.jl:160
 [3] cd(::##40#46, ::String) at ./file.jl:70
 [4] include_from_node1(::String) at ./loading.jl:569
 [5] include(::String) at ./sysimg.jl:14
 [6] process_options(::Base.JLOptions) at ./client.jl:305
 [7] _start() at ./client.jl:371
```

We're getting a lot of these messages like:

```
warning: parsing line table prologue at 0x0001bb18 should have ended at 0x0001beac but it ended at 0x0001bbf7
```

...in the build log. Am I reading the error message correctly that this is the cause of that test failure? Those messages are getting mixed up in the test input?

**Comment by jakirkham** [comment]
IDK about the warnings causing the issue though. We have those warnings already in the [latest 0.5 build]( https://circleci.com/gh/conda-forge/julia-feedstock/30 ). So if they were to cause issues, would have expected that to happen already. I *think* the failure here is unrelated.

**Comment by dfornika** [comment]
There's a new section of the `spawn` test that's not present in `v0.5.2`.

```
# issue #19864 (PR #20497)
@test readchomp(pipeline(ignorestatus(
        `$exename --startup-file=no -e '
            struct Error19864 <: Exception; end
            Base.showerror(io::IO, e::Error19864) = print(io, "correct19864")
            throw(Error19864())'`),
    stderr=catcmd)) == "ERROR: correct19864"
```

https://github.com/JuliaLang/julia/issues/19864

**Comment by jakirkham** [comment]
So we don't build in an interactive terminal. Not sure if that matters for this test or not.

**Comment by tkelman** [comment]
If you're getting a bunch of warnings from llvm on startup, something is broken

**Comment by jakirkham** [comment]
Not seeing these warning when starting up Julia. Only seeing them peppered throughout the tests.

**Comment by dfornika** [comment]
I do see those messages in an interactive julia session with the current `v0.5.2` build. They don't come up after a valid expression but do come up during an error. 

```
[dfornika@sabin ~]$ source activate julia
(julia) [dfornika@sabin ~]$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.2
 _/ |\__'_|_|_|\__'_|  |  conda-forge-julia release
|__/                   |  x86_64-unknown-linux-gnu

julia> 2 + 2
4

julia> akljdsfl
warning: parsing line table prologue at 0x0000e1c8 should have ended at 0x0000e52f but it ended at 0x0000e284
warning: parsing line table prologue at 0x00003c27 should have ended at 0x00003ffc but it ended at 0x00003ce3
warning: parsing line table prologue at 0x0001cd5c should have ended at 0x0001d0f0 but it ended at 0x0001ce25
warning: parsing line table prologue at 0x000086e2 should have ended at 0x00008ae4 but it ended at 0x000087ef
warning: parsing line table prologue at 0x0000a9c0 should have ended at 0x0000ace8 but it ended at 0x0000aa7c
ERROR: UndefVarError: akljdsfl not defined

julia> 
```

**Comment by dfornika** [comment]
Not sure how helpful this is, but this is the llvm function where the error originates:

http://llvm.org/doxygen/structllvm_1_1DWARFDebugLine_1_1Prologue.html#a8da40bebd23f4bbc9a1cd4e85df665ab

**Comment by dfornika** [comment]
```
julia> exename = Base.julia_cmd()
`/home/dfornika/miniconda2/envs/julia/bin/julia -Ccore2 -J/home/dfornika/miniconda2/envs/julia/lib/julia/sys.so --compile=yes --depwarn=yes`

catcmd = `cat`
`cat`

julia> readchomp(pipeline(ignorestatus(`$exename --startup-file=no -e 'struct Error19864 <: Exception; end Base.showerror(io::IO, e::Error19864) = print(io, "correct19864") throw(Error19864())'`), stderr=catcmd))
"warning: parsing line table prologue at 0x0001cd5c should have ended at 0x0001d0f0 but it ended at 0x0001ce25\nwarning: parsing line table prologue at 0x0000e1c8 should have ended at 0x0000e52f but it ended at 0x0000e284\nwarning: parsing line table prologue at 0x000086e2 should have ended at 0x00008ae4 but it ended at 0x000087ef\nwarning: parsing line table prologue at 0x0000a9c0 should have ended at 0x0000ace8 but it ended at 0x0000aa7c\nwarning: parsing line table prologue at 0x0001357a should have ended at 0x0001390c but it ended at 0x00013636\nwarning: parsing line table prologue at 0x00003c27 should have ended at 0x00003ffc but it ended at 0x00003ce3\nwarning: parsing line table prologue at 0x00000000 should have ended at 0x0000041a but it ended at 0x00000151\nERROR: syntax: extra token \"Error19864\" after end of expression\n in eval(::Module, ::Any) at ./boot.jl:234\n in process_options(::Base.JLOptions) at ./client.jl:242\n in _start() at ./client.jl:321"

julia> 
```

**Comment by jakirkham** [comment]
An interesting test would be to see if we get the same behavior from Julia during the build. It's possible that prefix replacement by `conda-build` ends up causing us some issues.

**Comment by jakirkham** [comment]
Toggling for CIs.

**Comment by jakirkham** [comment]
Appears this is now passing. 🎉 If there is nothing else, I think we should merge this.

**Comment by dfornika** [comment]
Great work!

**Pull request merged**
