### PR TITLE
Update pins on v0.6.1

### PR DESCRIPTION
**Pull request by dfornika**

### CODE REVIEW

**Comment by jakirkham** [comment]
Would update `arpack` -> `arpack 3.5.*` based on the current pinnings. Also could you please send a PR with the `libgit2` pinning over to the pinning file at the webpage repo?

**Comment by dfornika** [comment]
Sorry, I'm not sure what you mean by the pinning file. Should I add `libgit2 0.25.1` to https://github.com/conda-forge/conda-forge.github.io/edit/master/scripts/pin_the_slow_way.py ?

**Comment by jakirkham** [comment]
Correct.

**Comment by SylvainCorlay** [comment]
Hey @dfornika do you have updates on the Julia conda packaging for Julia? Is this something you are still working on?

**Comment by dfornika** [comment]
I haven't been actively working on this recently. My motivation for setting up the julia conda package was to enable automated installation of this bioinformatics tool: https://github.com/WGS-TB/MentaLiST in the Galaxy workflow manager. Now that we have a usable julia package for that project I've had to shift my focus to other responsibilities.

There are also just some issues with managing dependencies, patches and the continuous integration system that are beyond my level of expertise to diagnose and fix.

I know that they've just released a new release of the v0.6 branch and are marching towards v0.7 and v1.0, so I don't want to see these packages fall too far behind but I think someone else will need to take a lead in pushing it along.

**Comment by bgruening** [comment]
Closing in favor of 1.0.

**Pull request closed without merging**
