### PR TITLE
Updated to v0.6.2

### LINKED ISSUE #43: Update Julia version
0.6.2 is not included

### PR DESCRIPTION
**Pull request by dfornika**
Fixes #43

### CODE REVIEW

**Comment by dfornika** [comment]
CI timed out during testing phase. This is a known issue and it non-deterministic so I'll close and re-open to re-trigger a CI build.

**Comment by jakirkham** [comment]
CircleCI unfortunately doesn’t trigger a rebuild on reopen. It needs to be triggered through the web interface instead.

**Comment by dfornika** [comment]
@jakirkham Thanks, I thought I had done that in the past but maybe it was for TravisCI.

**Comment by jakirkham** [comment]
Interesting. If it has changed, that would be good to know. Had opened [this issue with CircleCI]( https://discuss.circleci.com/t/trigger-a-new-build-when-reopening-a-pr/13487 ) some time ago to get this fixed. Seems to have been rather quiet since.

**Comment by dfornika** [comment]
I've tried re-starting the CircleCI build several times but it times out during testing every time.

**Comment by jakirkham** [comment]
This is likely an indicator that one of the tests is using too much of some resource. Typically caused by too many threads. Would look and see if there is a way to restrict how many threads the tests use.

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by dfornika** [comment]
Still timing out during testing. Last bit of the log file looks like this:

```
+ source /opt/conda/bin/activate /feedstock_root/build_artefacts/julia_1516954260071/_t_env
+ /bin/bash -x -e /feedstock_root/build_artefacts/julia_1516954260071/test_tmp/run_test.sh
+ OPENBLAS_NUM_THREADS=1
+ julia -e 'Base.runtests("all"); Base.runtests("pkg libgit2-online")'
Test (Worker)             | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
WARNING: Method definition ambig(Any, Integer) in module Test46Main_ambiguous at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/ambiguous.jl:7 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/ambiguous.jl:85.
Skipping Base.<|
Skipping Base.active_repl
Skipping Base.active_repl_backend
Skipping Base.<|
Skipping Base.active_repl
Skipping Base.active_repl_backend
ambiguous (1)             |    2.17  |  0.13  |  6.1 | 38.61      | 217.64  
linalg/triangular (1)     |  270.59  |  9.58  |  3.5 | 9028.73    | 592.68  
linalg/qr (1)             |   50.81  |  1.98  |  3.9 | 2232.66    | 681.30  
linalg/dense (1)          |   76.99  |  2.09  |  2.7 | 2584.55    | 756.87  
linalg/matmul (1)         |   61.64  |  1.61  |  2.6 | 2377.98    | 761.90  
linalg/schur (1)          |    6.30  |  0.20  |  3.2 | 284.61     | 762.88  
linalg/special (1)        |   17.45  |  0.39  |  2.2 | 430.01     | 772.74  
linalg/eigen (1)          |    6.56  |  0.12  |  1.8 | 148.73     | 783.44  
linalg/bunchkaufman (1)   |    3.89  |  0.08  |  2.0 | 70.85      | 785.85  
linalg/svd (1)            |    6.08  |  0.12  |  2.0 | 147.46     | 788.73  
linalg/lapack (1)         |   19.12  |  0.61  |  3.2 | 691.56     | 807.91  
linalg/tridiag (1)        |   16.04  |  0.62  |  3.9 | 427.18     | 812.06  
linalg/bidiag (1)         |   22.06  |  0.37  |  1.7 | 360.25     | 840.86  
linalg/diagonal (1)       |   36.57  |  0.83  |  2.3 | 825.76     | 853.68  
linalg/pinv (1)           |    3.87  |  0.29  |  7.4 | 589.73     | 942.26  
linalg/givens (1)         |    3.32  |  0.08  |  2.5 | 70.12      | 942.26  
linalg/cholesky (1)       |   20.46  |  0.68  |  3.3 | 398.19     | 942.26  
linalg/lu (1)             |   19.38  |  0.82  |  4.2 | 724.85     | 942.26  
linalg/symmetric (1)      |    9.20  |  0.23  |  2.5 | 206.30     | 942.26  
linalg/generic (1)        |    5.82  |  0.16  |  2.7 | 111.50     | 942.26  
linalg/uniformscaling (1) |   12.02  |  0.29  |  2.4 | 249.81     | 943.19  
linalg/lq (1)             |   33.65  |  1.88  |  5.6 | 2779.71    | 1019.83 
linalg/hessenberg (1)     |    0.85  |  0.02  |  2.2 | 16.19      | 1021.18 
linalg/rowvector (1)      |   15.13  |  0.62  |  4.1 | 358.20     | 1037.34 
linalg/conjarray (1)      |    1.23  |  0.03  |  2.1 | 27.39      | 1037.34 
linalg/arnoldi (1)        |   18.09  |  0.55  |  3.0 | 509.11     | 1056.04 
subarray (1)              |  187.39  |  8.90  |  4.7 | 5064.78    | 1288.00 
sparse/sparse (1)         |  137.15  | 81.04  | 59.1 | 1077.11    | 1370.35 
sparse/sparsevector (1)   |   84.57  |  2.40  |  2.8 | 1319.33    | 1434.78 
sparse/higherorderfns (1) |  133.15  |  5.73  |  4.3 | 3055.12    | 1546.55 
sparse/umfpack (1)        |    5.25  |  0.18  |  3.3 | 78.01      | 1549.21 
sparse/cholmod (1)        |   18.52  |  1.12  |  6.0 | 259.65     | 1562.91 
sparse/spqr (1)           |    1.71  |  0.05  |  2.9 | 28.65      | 1562.91 
strings/basic (1)         |    6.26  |  0.23  |  3.7 | 118.91     | 1562.91 
strings/search (1)        |    1.31  |  0.05  |  3.8 | 15.61      | 1562.91 
strings/util (1)          |    0.68  |  0.00  |  0.0 |  8.75      | 1562.91 
strings/io (1)            |    1.28  |  0.09  |  7.2 | 29.43      | 1562.91 
strings/types (1)         |    4.39  |  0.05  |  1.0 | 18.70      | 1562.91 
unicode/UnicodeError (1)  |    0.02  |  0.00  |  0.0 |  0.17      | 1562.91 
unicode/utf8proc (1)      |    3.01  |  0.09  |  3.1 | 40.05      | 1562.91 
unicode/utf8 (1)          |    2.35  |  1.22  | 52.1 | 930.15     | 1562.91 
dates/accessors (1)       |    8.42  |  4.31  | 51.2 | 3477.88    | 1566.48 
dates/adjusters (1)       |    2.27  |  0.09  |  4.1 | 37.86      | 1568.84 
dates/query (1)           |    0.68  |  0.00  |  0.0 |  9.71      | 1568.84 
dates/periods (1)         |   12.01  |  0.45  |  3.7 | 184.03     | 1574.27 
dates/ranges (1)          |   12.67  |  0.77  |  6.1 | 416.59     | 1610.55 
dates/rounding (1)        |    0.54  |  0.00  |  0.0 |  5.57      | 1610.55 
dates/types (1)           |    0.94  |  0.05  |  4.8 | 13.06      | 1612.92 
dates/io (1)              |   11.78  |  0.36  |  3.1 | 178.65     | 1613.38 
dates/arithmetic (1)      |    5.18  |  0.20  |  3.8 | 98.41      | 1615.09 
dates/conversions (1)     |    0.68  |  0.00  |  0.0 |  5.31      | 1615.48 
WARNING: Method definition f() in module JLCall14301 at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:3427 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:3437.
WARNING: static parameter T does not occur in signature for bad_tvars at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4569.
The method will not be callable.
WARNING: Method definition (::Type{Test4Main_core.A16424})(Any, Any) in module Test4Main_core at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4772 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4777.
WARNING: Method definition (::Type{Test4Main_core.B16424{T}})(Any) in module Test4Main_core at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4792 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4796.
WARNING: Method definition (::Type{Test4Main_core.C16424{T, S}})(Any, Any) in module Test4Main_core at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4804 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4809.
WARNING: Method definition (::Type{Test4Main_core.C16424{T, S} where S where T})(T, S) in module Test4Main_core at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4804 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4809.
WARNING: Method definition (::Type{Test4Main_core.D16424{T<:Real, S<:T<:Real}})(Any, Any) in module Test4Main_core at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4819 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4824.
WARNING: Method definition (::Type{Test4Main_core.D16424{T, S} where S<:T where T<:Real})(Array{S<:T<:Real, 1}, Array{T<:Real, 1}) in module Test4Main_core at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4819 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4824.
WARNING: Method definition (::Type{Test4Main_core.T20999})(Array{T, N} where N where T<:Real) in module Test4Main_core at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4835 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4839.
WARNING: Method definition (::Type{Test4Main_core.T20999})(Any) in module Test4Main_core at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4835 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/core.jl:4839.
core (1)                  |   52.48  | 23.63  | 45.0 | 5038.05    | 1977.90 
inference (1)             |    4.15  |  0.10  |  2.5 | 47.59      | 1977.90 
WARNING: Method definition f265a(Any) in module Test17Main_worlds at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/worlds.jl:12 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/worlds.jl:17.
worlds (1)                |    1.49  |  0.06  |  3.8 | 19.92      | 1977.90 
keywordargs (1)           |    1.98  |  0.06  |  3.0 | 21.14      | 1977.90 
numbers (1)               |   59.59  |  2.90  |  4.9 | 1345.03    | 1977.90 
WARNING: Method definition test(Type{Tuple{V<:Union{Tuple{Int64, Int64}, Tuple{Int32, Int32}, Tuple{UInt64, UInt64}, Tuple{UInt32, UInt32}, Tuple{Int64, Int64, Int64}, Tuple{Int32, Int32, Int32}, Tuple{UInt64, UInt64, UInt64}, Tuple{UInt32, UInt32, UInt32}, Tuple{Int64, Int64, Int64, Int64}, Tuple{Int32, Int32, Int32, Int32}, Tuple{UInt64, UInt64, UInt64, UInt64}, Tuple{UInt32, UInt32, UInt32, UInt32}}, I<:Union{Int64, Int32, UInt64, UInt32}}}) in module Test44Main_subtype at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/subtype.jl:1111 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/subtype.jl:1112.
subtype (1)               |   21.15  |  1.91  |  9.0 | 602.78     | 1992.96 
printf (1)                |   16.05  |  1.03  |  6.4 | 199.30     | 1996.13 
char (1)                  |    0.92  |  0.05  |  5.1 | 13.02      | 1996.13 
triplequote (1)           |    0.02  |  0.00  |  0.0 |  0.26      | 1996.13 
intrinsics (1)            |    0.35  |  0.00  |  0.0 |  2.91      | 1996.13 
dict (1)                  |   17.31  |  0.78  |  4.5 | 331.59     | 1996.13 
hashing (1)               |    4.56  |  0.16  |  3.6 | 74.24      | 1996.13 
iobuffer (1)              |    1.88  |  0.10  |  5.5 | 39.32      | 1996.13 
WARNING: Method definition f10178(X) in module Test67Main_staged at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/staged.jl:218 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/staged.jl:223.
WARNING: Method definition g10178(Any) in module Test67Main_staged at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/staged.jl:220 overwritten at /feedstock_root/build_artefacts/julia_1516954260071/_t_env/share/julia/test/staged.jl:225.
staged (1)                |    0.92  |  0.00  |  0.0 |  8.72      | 1996.13 
offsetarray (1)           |   53.02  |  2.83  |  5.3 | 1037.20    | 1997.50 
arrayops (1)              |   71.39  |  3.95  |  5.5 | 1312.15    | 2161.98 
tuple (1)                 |    2.38  |  0.12  |  5.1 | 35.72      | 2161.98 
reduce (1)                |    4.80  |  0.24  |  4.9 | 86.79      | 2161.98 
reducedim (1)             |   13.61  |  0.71  |  5.2 | 265.00     | 2161.98 
random (1)                |   10.37  |  0.55  |  5.3 | 211.82     | 2161.98 
abstractarray (1)         |   50.38  |  2.90  |  5.8 | 821.46     | 2161.98 
intfuncs (1)              |    0.82  |  0.07  |  8.0 |  7.71      | 2161.98 
simdloop (1)              |    1.12  |  0.00  |  0.0 | 14.40      | 2161.98 
vecelement (1)            |   11.25  |  0.30  |  2.7 | 94.47      | 2161.98 
blas (1)                  |   18.42  |  0.96  |  5.2 | 360.79     | 2161.98 
bitarray (1)              |  248.70  |  6.15  |  2.5 | 2410.18    | 2196.59 
copy (1)                  |    1.60  |  0.07  |  4.1 | 17.93      | 2196.59 
math (1)                  |   20.26  |  2.20  | 10.9 | 1214.78    | 2203.98 
fastmath (1)              |    3.09  |  0.06  |  2.0 | 40.22      | 2207.72 
functional (1)            |    3.66  |  0.19  |  5.2 | 52.74      | 2208.27 
iterators (1)             |   26.13  |  0.96  |  3.7 | 346.66     | 2242.10 
operators (1)             |    2.92  |  0.18  |  6.1 | 60.78      | 2244.69 
path (1)                  |    2.19  |  0.77  | 35.1 | 15.87      | 2244.69 
ccall (1)                 |    7.93  |  0.25  |  3.2 | 78.37      | 2244.69 
parse (1)                 |    3.40  |  0.06  |  1.8 | 34.52      | 2244.69 
loading (1)               |    0.25  |  0.00  |  0.0 |  2.31      | 2244.69 
bigint (1)                |    1.88  |  0.12  |  6.3 | 23.57      | 2244.69 
bigfloat (1)              |    0.05  |  0.00  |  0.0 |  0.48      | 2244.69 
sorting (1)               |   36.60  |  1.14  |  3.1 | 454.46     | 2270.08 
statistics (1)            |    9.94  |  0.53  |  5.3 | 170.45     | 2285.79 
       [stdio passthrough ok]
spawn (1)                 |   19.93  |  2.59  | 13.0 | 555.49     | 2830.82 
backtrace (1)             |    0.50  |  0.00  |  0.0 |  2.68      | 2832.82 
Too long with no output (exceeded 10m0s)
```

**Comment by bgruening** [comment]
Closing in favor of 1.0.

**Pull request closed without merging**
