### PR TITLE
Adding support for julia-0.6.0

### PR DESCRIPTION
**Pull request by abhi18av**
Will correct the `sha256sum` as travis instructs.

### CODE REVIEW

**Comment by abhi18av** [comment]
Whoops the Circle-CI build fails with the following error 

```

ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.6.0
Platform Info:
  OS: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas.so
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

Stacktrace:
 [1] runtests(::String, ::Int64) at ./interactiveutil.jl:670
 [2] runtests(::String) at ./interactiveutil.jl:659
TESTS FAILED: julia-0.6.0-blas_openblas_1.tar.bz2
+ exit 1
Exited with code 1

```

**Comment by dfornika** [comment]
Hi @abhi18av, thanks for the PR but this is a duplicate of #7.

**Comment by abhi18av** [comment]
Ah, man! 

@dfornika I do hope that we can make `julia-0.6` available soon.

**Comment by jakirkham** [comment]
Thanks for your interest @abhi18av.

The `sha256sum` is a red herring. This is used by Travis CI to handle caching, which can work without `sha256sum`. Currently we are only building for Linux on CircleCI.

If you are wanting to push this forward, would take a look at PR ( https://github.com/conda-forge/julia-feedstock/pull/7 ) and the failure at the end of the log on CircleCI. If you have any ideas, please just submit a PR against @dfornika's branch. Thanks!

**Pull request closed without merging**
