### PR TITLE
WIP: Use ccache-toolchain

### PR DESCRIPTION
**Pull request by jakirkham**
Try using the `ccache-toolchain` to take advantage of `ccache`'s compilation caching in the hopes of further speeding up this build.

### CODE REVIEW

**Comment by isuruf** [comment]
You need to rerender using https://github.com/conda-forge/conda-smithy/pull/526

**Comment by jakirkham** [comment]
Do we get any benefits from using `ccache` without that re-rendering?

**Comment by isuruf** [comment]
Not really

**Comment by jakirkham** [comment]
Also should I be using `ccache-toolchain` or `toolchain3`?

**Comment by isuruf** [comment]
`ccache-toolchain` is what's needed.

**Comment by isuruf** [comment]
conda-forge/conda-smithy#526 is stalled because I didn't have time to test it. If you can test it here, that'd be great.

**Pull request closed without merging**
