### PR TITLE
Bump build number to trigger rebuild

### PR DESCRIPTION
**Pull request by mkitti**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin rerender

**Comment by mkitti** [comment]
Why does the packaging / test step use libunwind 1.6.2 still?

```
2021-12-21T05:23:23.3775413Z     libunwind:         1.6.2-h9c3ff4c_0           conda-forge
```

**Comment by ngam** [comment]
> Why does the packaging / test step use libunwind 1.6.2 still?
> 
> ```
> 2021-12-21T05:23:23.3775413Z     libunwind:         1.6.2-h9c3ff4c_0           conda-forge
> ```

would `pin_compatible` help here?

**Comment by mkitti** [comment]
@isuruf any thoughts about why libunwind 1.6.2-h9c3ff4c_0 is still showing up here during testing?

So far ngam suggests `pin_compatible` may be needed as well. @wolfv suggested I look at runexports.

**Comment by ngam** [comment]
> So far ngam suggests `pin_compatible` may be needed as well. 

I retract, I don't think this makes any sense, sorry...

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

I think it should default to 1.5, I have it working fine locally. So let's try to rerender.

```
    libopenblas:       0.3.18-pthreads_h8fe5266_0 conda-forge
    libopenblas-ilp64: 0.3.18-pthreads_h0aa5bea_0 conda-forge
    libssh2:           1.10.0-ha35d2d1_2          conda-forge
    libstdcxx-ng:      11.2.0-he4da1e4_11         conda-forge
    libunwind:         1.5.0-h9c3ff4c_1           conda-forge
    libutf8proc:       2.7.0-h7f98852_0           conda-forge
    libzlib:           1.2.11-h36c2ea0_1013       conda-forge
    mbedtls:           3.1.0-h9c3ff4c_0           conda-forge
    metis:             5.1.0-h58526e2_1006        conda-forge
    mpfr:              4.1.0-h9202a9a_1           conda-forge

```

**Comment by ngam** [comment]
Oh well, lol 

it is 1.5 here #144

**Comment by ngam** [comment]
I am testing now with `pin_run_as_build`...

**Comment by ngam** [comment]
> Why does the packaging / test step use libunwind 1.6.2 still?
> 
> ```
> 2021-12-21T05:23:23.3775413Z     libunwind:         1.6.2-h9c3ff4c_0           conda-forge
> ```

`pin_run_as_build` is the answer, not sure why that wsn't implemented by default like other global pins. Follow along in #144 to see if it can go through...

**Pull request merged**
