### PR TITLE
testing Downloads per mk request

### PR DESCRIPTION
**Pull request by ngam**
Co-authored-by: mkitti <mkitti@users.noreply.github.com>

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
Local testing based on v1.7.1 linux64:

3 failures:

```
share/julia/stdlib/v1.7/Downloads/test/runtests.jl:439
  Test threw exception
  Expression: resp.status == 200
  type RequestError has no field status
```

```
share/julia/stdlib/v1.7/Downloads/test/runtests.jl:447
  Expression: resp isa Response
   Evaluated: Downloads.RequestError("https://wrong.host.badssl.com", 60, "SSL: no alternative certificate subject name matches target host name 'wrong.host.badssl.com'", Downloads.Response("https", "https://wrong.host.badssl.com/", 0, "", Pair{String, String}[])) isa Downloads.Response
```

```
share/julia/stdlib/v1.7/Downloads/test/runtests.jl:448
  Test threw exception
  Expression: resp.status == 200
  type RequestError has no field status
```

**Comment by ngam** [comment]
```julia
419         @testset "easy hook work-around" begin
420             local url
421             easy_hook = (easy, info) -> begin
422                 Curl.set_ssl_verify(easy, false)
423                 @test info.url == url
424             end
425             # downloader-specific easy hook
426             downloader = Downloader()
427             downloader.easy_hook = easy_hook
428             for outer url in urls
429                 resp = request(url, throw=false, downloader=downloader)
430                 @test resp isa Response
431                 @test resp.status == 200
432             end
433             # default easy hook
434             Downloads.EASY_HOOK[] = easy_hook
435             Downloads.DOWNLOADER[] = nothing
436             for outer url in urls
437                 resp = request(url, throw=false)
438                 @test resp isa Response
439                 @test resp.status == 200
440             end
441             Downloads.DOWNLOADER[] = nothing
442             Downloads.EASY_HOOK[] = nothing
443         end
444         ENV["JULIA_SSL_NO_VERIFY_HOSTS"] = "**.badssl.com"
445         @testset "SSL no verify override" for url in urls
446             resp = request(url, throw=false)
447             @test resp isa Response
448             @test resp.status == 200
449         end
450         delete!(ENV, "JULIA_SSL_NO_VERIFY_HOSTS")
451     end

```

**Comment by ngam** [comment]
@conda-forge-admin, please rerender

**Comment by ngam** [comment]
@mkitti, I suspect this is a `curl` issue from reading upstream, hence trying to see use their curl to see if it resolves the issue. Otherwise, I have no idea what's going on...

**Comment by mkitti** [comment]
See upstream https://github.com/JuliaLang/Downloads.jl/issues/139

**Comment by mkitti** [comment]
This is an upstream issue. I propose closing this. Merging #157. Create a new PR from master pulling https://github.com/JuliaLang/julia/commit/f61eb87cd82f573f008d011c95be7d6fd8c68584 . Retest Downloads.jl. Inform upstream via the issue above if the issue is resolved.

**Comment by ngam** [comment]
Okay, will do.

**Pull request closed without merging**
